# **Install & Load Dataset**

In [ ]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.20.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.6.17)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.14.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (0.1.2)

In [ ]:
from datasets import load_dataset

In [ ]:
dataset = load_dataset("CShorten/ML-ArXiv-Papers" , split = 'train')

README.md:   0%|          | 0.00/986 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

ML-Arxiv-Papers.csv:   0%|          | 0.00/147M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/117592 [00:00<?, ? examples/s]

In [ ]:
print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})

In [ ]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'}

# **DataFrame Creation**

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(dataset)

In [ ]:
df

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...,...,...
117587,4995,NaN,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,4996,NaN,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,4997,NaN,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,4998,NaN,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,4999,NaN,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [ ]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [ ]:
df = df[ ['title' , 'abstract'] ]

In [ ]:
df.shape

(15000, 2)

In [ ]:
df = df.head(15000)

In [ ]:
df.shape

(15000, 2)

In [ ]:
df.isnull().sum()

title       0
abstract    0
dtype: int64

In [ ]:
df["paper_text"] = df["title"] + " " + df["abstract"]

In [ ]:
df["paper_text"].head()

0    Learning from compressed observations   The pr...
1    Sensor Networks with Random Links: Topology De...
2    The on-line shortest path problem under partia...
3    A neural network approach to ordinal regressio...
4    Parametric Learning and Monte Carlo Optimizati...
Name: paper_text, dtype: object

In [ ]:
df[["paper_text"]].head()

                                          paper_text
0  Learning from compressed observations   The pr...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

In [ ]:
type(df["paper_text"].iloc[0])

str

# **SentenceTransformer**

In [ ]:
from sentence_transformers import SentenceTransformer

In [ ]:
model = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>

In [ ]:
df["paper_text"] = df["paper_text"].str.replace("\n", " ",regex=False)

In [ ]:
df["paper_text"] = df["paper_text"].str.strip()

# **Embedding [of 1]**

In [ ]:
sample_text = df["paper_text"].iloc[0]

In [ ]:
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regression in Gaussian noise.'

In [ ]:
embedding = model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

<class 'numpy.ndarray'>
(384,)

In [ ]:
embedding[:56]

array([-0.1315641 , -0.00678266, -0.00367612,  0.03265158,  0.11219642,
        0.01227267,  0.09816719, -0.0900523 ,  0.04231161, -0.01977348,
       -0.03308417,  0.07452948,  0.10632038, -0.02060429, -0.02052106,
        0.00169493,  0.07081953,  0.05854454, -0.11231912,  0.02082474,
        0.05692544,  0.0201578 ,  0.0258311 ,  0.0321703 ,  0.10513764,
       -0.09676763,  0.02700802, -0.0234509 , -0.04549678, -0.01013699,
       -0.01794855, -0.04814427,  0.01077652, -0.03759069,  0.01943481,
        0.03715189,  0.02967844,  0.04330941,  0.04373213,  0.03704866,
       -0.00182594,  0.00455183, -0.00799067,  0.03037368, -0.014378  ,
        0.03795147,  0.0595916 , -0.02583356, -0.06521576,  0.05900268,
       -0.02107134,  0.07359422, -0.05720106,  0.00294061,  0.00767515,
       -0.0333416 ], dtype=float32)

# **Embedding [of 5]**

In [ ]:
sample_of_5_embedding = model.encode(df["paper_text"].head(5).to_list())

In [ ]:
print(sample_of_5_embedding.shape)

(5, 384)

In [ ]:
sample_of_5_embedding

array([[-0.1315641 , -0.00678266, -0.0036761 , ...,  0.09561252,
        -0.04423944,  0.00522624],
       [-0.03589668, -0.06343269, -0.00394966, ...,  0.07206137,
        -0.13262011, -0.00412079],
       [-0.08129284,  0.024103  , -0.08868261, ..., -0.04524419,
        -0.0476585 , -0.01549932],
       [-0.10218991, -0.06282566,  0.03273673, ..., -0.03118814,
         0.03174181,  0.03621249],
       [-0.08391042,  0.01838467, -0.01556663, ..., -0.01188403,
        -0.10644462,  0.00790998]], dtype=float32)

# **Cosine Similarity [of 5]**

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity = cosine_similarity(sample_of_5_embedding[0].reshape(1, -1) , sample_of_5_embedding[0].reshape(1, -1))
print(similarity)

[[1.0000001]]

In [ ]:
similarity = cosine_similarity(sample_of_5_embedding[0].reshape(1, -1) , sample_of_5_embedding[1].reshape(1, -1))
print(similarity)

[[0.36625272]]

In [ ]:
for i in range(0,5):
  sim  = cosine_similarity(sample_of_5_embedding[0].reshape(1, -1), sample_of_5_embedding[i].reshape(1, -1))
  print(sim)

[[1.0000001]]
[[0.36625272]]
[[0.33522844]]
[[0.15505108]]
[[0.37421533]]

# **FAISS [of 5]**

In [ ]:
!pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.14.3-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)
Downloading faiss_cpu-1.14.3-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 33.7 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.14.3

In [ ]:
import faiss

In [ ]:
faiss.normalize_L2(sample_of_5_embedding)

In [ ]:
index = faiss.IndexFlatIP(384)

In [ ]:
print(index.ntotal)

0

In [ ]:
index.add(sample_of_5_embedding)

In [ ]:
print(index.ntotal)

5

In [ ]:
query = "deep learning for medical image analysis"

In [ ]:
query_embedding = model.encode(query)
query_embedding.shape

(384,)

In [ ]:
query_embedding.reshape(1,-1)

array([[-3.52526233e-02,  5.43267392e-02,  5.65811694e-02,
        -4.97096516e-02, -3.52174975e-02, -2.67348643e-02,
        -8.23498983e-03,  1.52610382e-02, -1.31555051e-02,
        -5.45782186e-02, -5.26165627e-02, -1.20118475e-02,
        -8.10011625e-02,  9.73842591e-02, -1.15813181e-01,
        -1.68417636e-02, -9.74307284e-02, -5.52448351e-03,
        -1.06863692e-01,  7.64734065e-03, -4.89181019e-02,
        -6.45619398e-03, -3.65177542e-02,  2.23113876e-02,
         5.65221906e-02,  4.34993301e-03,  6.29342273e-02,
        -1.09063022e-01,  3.48554738e-02, -1.03746569e-02,
         7.24759325e-02, -3.63332927e-02,  1.78154279e-02,
         1.52815776e-02,  4.68111634e-02,  7.27785826e-02,
        -1.72747560e-02,  5.71634062e-02,  6.73012529e-03,
         2.91874819e-02,  4.84563038e-02,  5.15045710e-02,
         3.13240252e-02,  5.97999133e-02,  8.63463730e-02,
        -1.21598854e-03,  3.83908153e-02, -1.21436063e-02,
         5.59613332e-02,  9.04098302e-02, -1.46837337e-02,
         2.19263099e-02, -7.75723755e-02,  8.67380574e-02,
         3.64489220e-02, -1.94059196e-03, -1.39827561e-02,
        -1.21371830e-02, -1.06874987e-01, -9.59572382e-03,
         4.63739224e-02,  2.24665124e-02,  5.43063506e-02,
         4.43859510e-02,  3.77480686e-02,  2.02459656e-02,
         2.08114907e-02,  5.34768961e-02, -4.54898402e-02,
         1.44555024e-03,  4.19528559e-02,  1.98635142e-02,
        -4.58728103e-03,  6.87859580e-02, -5.97209260e-02,
         1.62376859e-03,  5.95383197e-02,  4.62819859e-02,
         5.08468188e-02, -8.98064896e-02,  7.37257302e-02,
        -6.98515214e-04, -7.84180406e-03, -8.07955638e-02,
         9.51529741e-02, -7.67620876e-02,  1.81950480e-02,
         4.54610474e-02, -1.31773874e-01, -2.09247470e-02,
         7.16780350e-02,  1.44964987e-02, -6.97494159e-03,
        -2.19205432e-02,  3.26014087e-02, -3.51133496e-02,
         2.57652234e-02, -1.03119619e-01, -3.74533869e-02,
         4.53220606e-02, -3.39956135e-02, -5.69088347e-02,
         1.57614704e-02,  2.91841291e-02,  2.94610094e-02,
        -6.83691651e-02,  4.56289686e-02, -1.73709095e-02,
        -2.79328264e-02, -6.41006604e-02,  6.41437173e-02,
         7.77505636e-02,  5.92813641e-02,  2.91401315e-02,
         3.62111740e-02, -5.68554699e-02, -1.52982278e-02,
        -2.86054090e-02,  1.38805974e-02, -1.59941590e-03,
        -1.28154337e-01, -3.75411510e-02, -1.15341097e-01,
         3.14719602e-02,  5.19519337e-02, -8.93071294e-03,
        -6.25772104e-02, -1.35184872e-33, -1.87913273e-02,
        -2.28778906e-02,  4.02108282e-02,  2.38876068e-03,
         1.48277907e-02,  7.78050395e-03,  1.00906077e-03,
        -3.41362953e-02, -1.76648218e-02,  1.62180122e-02,
        -8.23881105e-02,  4.51603048e-02, -1.79737937e-02,
         3.72223184e-02,  3.04088704e-02,  8.37345496e-02,
         1.32518029e-02,  5.81286550e-02,  3.48317735e-02,
        -2.74575651e-02, -1.05539057e-02, -6.02569133e-02,
        -1.22812755e-01,  3.75632159e-02, -6.26040548e-02,
        -2.26908009e-02, -5.91862313e-02,  7.61472341e-03,
         4.46788110e-02, -2.25559846e-02, -8.54879022e-02,
         1.88312363e-02, -4.29808814e-03,  3.95027436e-02,
         2.51674391e-02,  1.82117019e-02, -8.63525644e-03,
         6.65913001e-02,  7.06070587e-02,  3.81814353e-02,
         3.37507017e-02,  5.43730482e-02,  1.41882049e-02,
        -1.17155546e-02,  4.45315652e-02,  6.93227723e-02,
         7.16811628e-04, -3.39555591e-02, -7.14667886e-02,
        -7.03819618e-02,  3.95714082e-02, -4.72997166e-02,
        -6.15625903e-02, -3.71804722e-02,  6.59012124e-02,
        -8.33534542e-03, -4.01296876e-02,  7.54566789e-02,
         2.90026031e-02,  8.46807566e-03,  1.55613184e-01,
         2.19233297e-02,  1.42956413e-02,  6.37941286e-02,
        -3.37166886e-04, -4.51205904e-03,  2.62482911e-02,
         7.25072110e-03, -8.76036356e-04, -2.23250557e-02,
        -9.72210094e-02,  1.12481952e-01, -2.30172239e-02,
        -1.04437552e-01,  1.90296341e-02,  6.69645518e-02,
         2.30250005e-02, -3.28353606e-02, -5.64100109e-02,
         1.86219104e-02, -2.40781978e-02,  7.99190179e-02,
        -5.83158853e-03,  4.30585205e-04, -1.13126999e-02,
        -3.89501266e-02,  2.69120466e-02,  4.30381251e-03,
        -4.06309590e-02, -2.19732355e-02, -7.91952088e-02,
         4.96795736e-02,  2.78964210e-02, -8.29582103e-03,
        -4.84471880e-02,  2.40533015e-33, -2.71919202e-02,
         8.16385671e-02, -9.97152086e-03,  4.23292676e-03,
         6.11569397e-02,  1.51171293e-02, -2.58374624e-02,
         1.00573730e-02,  3.69041003e-02,  5.00409938e-02,
         1.42777950e-01, -1.55318454e-02, -4.93554249e-02,
        -5.08601684e-03,  4.55454253e-02, -2.21154299e-02,
        -2.35829763e-02, -2.66794711e-02,  2.15414707e-02,
        -2.08830344e-03,  1.08220000e-02,  1.20718889e-01,
        -2.96739303e-02,  4.55560014e-02, -1.21766001e-01,
         7.10935984e-03, -1.46779511e-03, -3.94056141e-02,
        -2.88322046e-02, -7.39129409e-02, -4.11270931e-02,
        -9.09108520e-02, -4.23304625e-02, -6.83618523e-03,
        -7.49105774e-03,  8.12597275e-02,  8.96155369e-03,
        -4.77026738e-02,  6.74306741e-03,  2.76624300e-02,
         1.01024583e-01, -5.85775264e-02, -2.57794634e-02,
         3.83146852e-02, -6.03901483e-02, -9.36420634e-02,
         3.75826247e-02, -1.96465533e-02,  7.44182765e-02,
         5.72315380e-02, -1.59692690e-02, -6.92118332e-02,
        -1.54886972e-02, -6.68955548e-03, -7.05694705e-02,
        -6.99542556e-03, -1.97791047e-02, -4.67792340e-03,
         5.68661839e-02,  3.28516625e-02, -7.29308054e-02,
        -1.03879176e-01, -6.41866252e-02, -7.55348988e-03,
        -3.53590287e-02,  7.90074542e-02, -8.03860649e-03,
         5.20747229e-02, -7.04174116e-02,  9.26927328e-02,
         2.03139540e-02,  2.58511249e-02,  8.69477983e-04,
         1.11361951e-01,  2.95029879e-02, -8.62996951e-02,
         2.75607104e-03, -5.81436232e-02,  4.32723202e-02,
         4.73406492e-03,  1.06191769e-01, -8.48156661e-02,
         9.01140552e-03,  1.04959659e-01, -1.09804131e-03,
         4.79194410e-02, -2.00858107e-03, -7.70298094e-02,
        -3.78427543e-02, -2.20932811e-02, -1.50252448e-03,
         2.75487415e-02, -1.19331609e-02, -4.83060144e-02,
         4.98714261e-02, -1.31291769e-08, -4.94397618e-02,
         1.40069509e-02,  1.10468909e-01, -1.25301518e-02,
         3.12992968e-02, -6.11743182e-02, -4.24654074e-02,
         5.76240085e-02, -3.15740295e-02,  8.45370889e-02,
         9.69443657e-03, -3.57002504e-02, -7.08413869e-02,
        -4.89252768e-02,  1.27309812e-02,  1.11371920e-01,
        -2.75847409e-02,  2.57702675e-02,  2.41262168e-02,
        -4.18543108e-02, -1.36213144e-02,  5.39695844e-02,
         4.54969183e-02, -8.49933457e-03,  2.15128139e-02,
        -4.08058055e-02, -6.59219474e-02,  1.43205822e-02,
         3.10315937e-02,  2.44345237e-02,  1.80983692e-02,
         2.74739396e-02,  5.76358400e-02, -1.58118680e-02,
         4.37507443e-02,  4.40286100e-02, -2.43303496e-02,
        -2.07101684e-02, -1.00277197e-02, -2.14689467e-02,
        -1.33139258e-02,  1.85948890e-02, -1.87703911e-02,
        -7.06424788e-02, -3.41698751e-02, -3.35524380e-02,
         5.58721684e-02,  3.14374752e-02,  6.42178208e-03,
        -1.30479867e-02,  3.78712639e-02, -9.66782775e-03,
         1.14139423e-01,  5.03667966e-02, -2.37698518e-02,
         7.52232671e-02,  6.08101189e-02, -3.52711342e-02,
         2.87808459e-02,  1.18030868e-01, -4.29459438e-02,
         4.24703620e-02, -4.80294488e-02, -5.18466299e-03]], dtype=float32)

In [ ]:
query_embedding.shape

(384,)

In [ ]:
query_embedding = model.encode([query])
query_embedding.shape

(1, 384)

In [ ]:
faiss.normalize_L2(query_embedding)

In [ ]:
D, I = index.search(query_embedding, 5)

In [ ]:
print(D)
print(I)

[[0.24243258 0.17442387 0.14026146 0.07622977 0.01298682]]
[[3 4 0 2 1]]

# **Embedding [of all 15000]**

In [ ]:
import os
import numpy as np

if os.path.exists("paper_embeddings.npy"):
    print("Loading saved embeddings...")
    embeddings = np.load("paper_embeddings.npy")

else:
    print("Generating embeddings...")
    embeddings = model.encode(df["paper_text"].to_list() , batch_size=32 , show_progress_bar=True)
    np.save("paper_embeddings.npy", embeddings)
    print("Embeddings saved successfully!")

Loading saved embeddings...

In [ ]:
print(embeddings.shape)
print(type(embeddings))
embeddings.dtype

(15000, 384)
<class 'numpy.ndarray'>

dtype('float32')

# **FAISS [of 15000]**

In [ ]:
if os.path.exists("paper_faiss.index"):
    print("Loading existing FAISS index...")
    index = faiss.read_index("paper_faiss.index")

else:
    print("Creating new FAISS index...")
    faiss.normalize_L2(embeddings)
    index = faiss.IndexFlatIP(384)
    index.add(embeddings)

    faiss.write_index(index, "paper_faiss.index")
    print("FAISS index saved successfully!")

Loading existing FAISS index...

In [ ]:
print(index.ntotal)

15000

In [ ]:
query = "deep learning for medical image analysis"
query_embedding = model.encode([query])
query_embedding.shape
faiss.normalize_L2(query_embedding)
D, I = index.search(query_embedding, 5)
print(D) # Similarity Score
print(I) # Indices

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]
[[10466 13730 11873 12691 11282]]

In [ ]:
df.iloc[10466]["title"]

A Perspective on Deep Imaging

In [ ]:
df.iloc[10466]["abstract"]

  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

In [ ]:
df.iloc[11873]["title"]

'Classification of MRI data using Deep Learning and Gaussian\n  Process-based Model Selection'

In [ ]:
df.iloc[11873]["abstract"]

'  The classification of MRI images according to the anatomical field of view is\na necessary task to solve when faced with the increasing quantity of medical\nimages. In parallel, advances in deep learning makes it a suitable tool for\ncomputer vision problems. Using a common architecture (such as AlexNet)\nprovides quite good results, but not sufficient for clinical use. Improving the\nmodel is not an easy task, due to the large number of hyper-parameters\ngoverning both the architecture and the training of the network, and to the\nlimited understanding of their relevance. Since an exhaustive search is not\ntractable, we propose to optimize the network first by random search, and then\nby an adaptive search based on Gaussian Processes and Probability of\nImprovement. Applying this method on a large and varied MRI dataset, we show a\nsubstantial improvement between the baseline network and the final one (up to\n20\\% for the most difficult classes).\n'

# **Search [return]**

In [ ]:
def search_paper_return(query, k=5):
  # Generate query embedding
  query_embedding = model.encode([query])

  # Normalize query embedding
  faiss.normalize_L2(query_embedding)

  # Search in FAISS index
  D, I = index.search(query_embedding, k)

  return D, I

In [ ]:
D , I = search_paper_return("deep learning for medical image analysis")
print(D)
print(I)

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]
[[10466 13730 11873 12691 11282]]

# **Search [display - zip()]**

In [ ]:
def search_paper_display(query, k = 5):
  query_embedding = model.encode([query])
  faiss.normalize_L2(query_embedding)
  D, I = index.search(query_embedding, k)

  for rank, (score, idx) in enumerate(zip(D[0] , I[0]), start = 1):
      print()
      print("=" * 100)
      print()
      print(f"Result Rank        : #{rank}")

      print(f"Paper Index        : {idx}")

      print(f"Similarity Score   : {score:.4f}")

      print(f"\nTitle: {df.iloc[idx]['title']}")

      print(f"\nAbstract: {df.iloc[idx]['abstract'][:500]}")

In [ ]:
search_paper_display("deep learning for medical image analysis")

====================================================================================================

Result Rank        : #1
Paper Index        : 10466
Similarity Score   : 0.6807

Title: A Perspective on Deep Imaging

Abstract:   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

====================================================================================================

Result Rank        : #2
Paper Index        : 13730
Similarity Score   : 0.6709

Title: Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?

Abstract:   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra

====================================================================================================

Result Rank        : #3
Paper Index        : 11873
Similarity Score   : 0.6522

Title: Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection

Abstract:   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai

====================================================================================================

Result Rank        : #4
Paper Index        : 12691
Similarity Score   : 0.6281

Title: High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks

Abstract:   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th

====================================================================================================

Result Rank        : #5
Paper Index        : 11282
Similarity Score   : 0.6131

Title: Deep Learning for the Classification of Lung Nodules

Abstract:   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN ar

# **Summarize [BART]**

In [ ]:
!pip install transformers==4.46.3

Collecting transformers==4.46.3
  Downloading transformers-4.46.3-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 kB 2.3 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (3.29.4)
Collecting huggingface-hub<1.0,>=0.23.2 (from transformers==4.46.3)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2.32.4)
Collecting tokenizers<0.21,>=0.20 (from transformers==4.46.3)
  Downloading tokenizers-0.20.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (2026.6.17)
Downloading transformers-4.46.3-py3-none-any.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 88.0 MB/s eta 0:00:00
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 44.4 MB/s eta 0:00:00
Downloading tokenizers-0.20.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 92.4 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, tokenizers, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.20.1
    Uninstalling huggingface_hub-1.20.1:
      Successfully uninstalled huggingface_hub-1.20.1
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
  Attempting uninstall: transformers
    Found existing installation: transformers 5.12.1
    Uninstalling transformers-5.12.1:
      Successfully uninstalled transformers-5.12.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 6.19.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.36.2 which is incompatible.
Successfully installed huggingface-hub-0.36.2 tokenizers-0.20.3 transformers-4.46.3

In [ ]:
from transformers import pipeline

In [ ]:
summarizer = pipeline("summarization" , model = "facebook/bart-large-cnn")

KeyError: "Unknown task summarization, available tasks are ['any-to-any', 'audio-classification', 'automatic-speech-recognition', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-text-to-text', 'keypoint-matching', 'mask-generation', 'ner', 'object-detection', 'sentiment-analysis', 'table-question-answering', 'text-classification', 'text-generation', 'text-to-audio', 'text-to-speech', 'token-classification', 'video-classification', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection']"

In [ ]:
type(summarizer)

NameError: name 'summarizer' is not defined

In [ ]:
summary = summarizer(df.iloc[10466]["abstract"] , max_length = 120  ,min_length = 40)

In [ ]:
print(summary)

[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]

In [ ]:
type(summary)

In [ ]:
type(summary[0])

In [ ]:
summary[0]["summary_text"]

# **Search + Summarize**

In [ ]:
def search_and_summarize(query, k=5):

  query_embedding = model.encode([query])
  faiss.normalize_L2(query_embedding)

  D, I = index.search(query_embedding, k)

  for rank, (score, idx) in enumerate(zip(D[0], I[0]) , start = 1):
    print()
    print("=" * 100)
    print()

    print(f"Result Rank        : #{rank}")
    print(f"Paper Index        : {idx}")
    print(f"Similarity Score   : {score:.4f}")

    print(f"\nTitle:")
    print(df.iloc[idx]["title"])

    print(f"\nAbstract Preview:")
    print(df.iloc[idx]["abstract"][:500])

    # Generate summary
    summary = summarizer(df.iloc[idx]["abstract"] , max_length = 120, min_length = 40, do_sample = False)

    print("\nSummary:")
    print(summary[0]["summary_text"])
    print("\n")

In [ ]:
search_and_summarize("Deep learning in medical imaging" , k = 5)

# **Keyword**

In [ ]:
!pip install keybert

Collecting keybert
  Downloading keybert-0.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from keybert) (2.0.2)
Requirement already satisfied: rich>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from keybert) (13.9.4)
Requirement already satisfied: scikit-learn>=0.22.2 in /usr/local/lib/python3.12/dist-packages (from keybert) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.3.8 in /usr/local/lib/python3.12/dist-packages (from keybert) (5.6.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert) (2.20.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert) (4.46.3)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert) (0.36.2)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert) (2.11.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (1.5.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (2.32.4)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert) (0.1.2)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (2025.11.3)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (0.8.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (2026.6.17)
Downloading keybert-0.9.0-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.4/41.4 kB 1.9 MB/s eta 0:00:00
Installing collected packages: keybert
Successfully installed keybert-0.9.0

In [ ]:
from keybert import KeyBERT

ModuleNotFoundError: No module named 'keybert'

In [ ]:
kw_model = KeyBERT(model)

In [ ]:
type(kw_model) # model = SentenceTransformer("all-MiniLM-L6-v2")

keybert._model.KeyBERT

In [ ]:
text = df.iloc[10466]["abstract"]
keywords = kw_model.extract_keywords(text)

In [ ]:
print(keywords)

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]

In [ ]:
print(type(keywords))

<class 'list'>

In [ ]:
print(type(keywords[0]))

<class 'tuple'>

In [ ]:
keywords = kw_model.extract_keywords(text , keyphrase_ngram_range = (1, 3) , stop_words = "english")

In [ ]:
print(keywords)

[('tomographic imaging deep', 0.6704), ('imaging deep learning', 0.6543), ('learning medical imaging', 0.6041), ('imaging deep', 0.5919), ('medical imaging', 0.5281)]

# **Search + Summarize + Keyword**

In [ ]:
def search_summarize_keywords(query, k=5):
  query_embedding = model.encode([query])
  faiss.normalize_L2(query_embedding)
  D, I = index.search(query_embedding, k)

  for rank, (score, idx) in enumerate(zip(D[0], I[0]), start = 1):
    print()
    print("=" * 100)
    print()

    print(f"Result Rank        : #{rank}")
    print(f"Paper Index        : {idx}")
    print(f"Similarity Score   : {score:.4f}")

    print("\nTitle:")
    print(df.iloc[idx]["title"])

    print("\nAbstract Preview:")
    print(df.iloc[idx]["abstract"][:500])

    print()

    # Generate summary
    summary = summarizer( df.iloc[idx]["abstract"] , max_length = 120, min_length = 40, do_sample = False)
    print("Summary:")
    print(summary[0]["summary_text"])
    print()

    # Extract keywords from the abstract
    keywords = kw_model.extract_keywords( df.iloc[idx]["abstract"] , keyphrase_ngram_range = (1, 3), stop_words = "english")

    print("Keywords:")

    for keyword, score in keywords:
      print(keyword)
    print("\n")

In [ ]:
search_summarize_keywords("natural language processing using transformers", k = 5)

====================================================================================================

Result Rank        : #1
Paper Index        : 3677
Similarity Score   : 0.5540

Title:
Category-Theoretic Quantitative Compositional Distributional Models of
  Natural Language Semantics

Abstract Preview:
  This thesis is about the problem of compositionality in distributional
semantics. Distributional semantics presupposes that the meanings of words are
a function of their occurrences in textual contexts. It models words as
distributions over these contexts and represents them as vectors in high
dimensional spaces. The problem of compositionality for such models concerns
itself with how to produce representations for larger units of text by
composing the representations of smaller units of text.

Summary:
This thesis is about the problem of compositionality in distributional purposefullysemantics. It uses the categorical framework developed by Coecke, Sadrzadeh, and Clark. It shows how this approach can be practically implemented to produce concrete distributional models.

Keywords:
compositionality distributional semantics
distributional semantics
distributional semantics distributional
semantics distributional semantics
semantics distributional



====================================================================================================

Result Rank        : #2
Paper Index        : 9294
Similarity Score   : 0.5141

Title:
Word2Vec is a special case of Kernel Correspondence Analysis and Kernels
  for Natural Language Processing

Abstract Preview:
  We show that correspondence analysis (CA) is equivalent to defining a Gini
index with appropriately scaled one-hot encoding. Using this relation, we
introduce a nonlinear kernel extension to CA. This extended CA gives a known
analysis for natural language via specialized kernels that use an appropriate
contingency table. We propose a semi-supervised CA, which is a special case of
the kernel extension to CA. Because CA requires excessive memory if applied to
numerous categories, CA has not been

Summary:
 correspondence analysis (CA) is equivalent to defining a Giniindex with appropriately scaled one-hot encoding. Because CA requires excessive memory if applied tonumerous categories, CA has not been used for natural language processing. We introduce delayed evaluation to randomized singular value decomposition. The memory-efficient CA is then applied to a word- vectorrepresentation task.

Keywords:
skip gram kernel
natural language processing
language specialized kernels
gram kernel extension
gram kernel



====================================================================================================

Result Rank        : #3
Paper Index        : 3905
Similarity Score   : 0.5039

Title:
Factorial Hidden Markov Models for Learning Representations of Natural
  Language

Abstract Preview:
  Most representation learning algorithms for language and image processing are
local, in that they identify features for a data point based on surrounding
points. Yet in language processing, the correct meaning of a word often depends
on its global context. As a step toward incorporating global context into
representation learning, we develop a representation learning algorithm that
incorporates joint prediction into its technique for producing features for a
word. We develop efficient variatio

Summary:
In language processing, the correct meaning of a word often depends on its global context. We develop efficient variational methods for learning Factorial Hidden Hidden Markov Models from large texts. Experiments on part-of-speech tagging and chunking indicate that the features are competitive with or better than state of the art representation learning methods.

Keywords:
context representation learning
speech tagging chunking
representation learning algorithms
representation learning methods
context representation



====================================================================================================

Result Rank        : #4
Paper Index        : 9771
Similarity Score   : 0.5027

Title:
A Probabilistic Generative Grammar for Semantic Parsing

Abstract Preview:
  Domain-general semantic parsing is a long-standing goal in natural language
processing, where the semantic parser is capable of robustly parsing sentences
from domains outside of which it was trained. Current approaches largely rely
on additional supervision from new domains in order to generalize to those
domains. We present a generative model of natural language utterances and
logical forms and demonstrate its application to semantic parsing. Our approach
relies on domain-independent supervi

Summary:
Domain-general semantic parsing is a long-standing goal in natural language processing. We present a generative model of natural language utterances and logical forms. We implement efficient algorithms for training, parsing, and sentencegeneration. We also describe the novel application of hierarchical Dirichlet processes for structured prediction.

Keywords:
parsing sentences domains
general semantic parsing
parsing sentence generation
semantic parsing
training parsing sentence



====================================================================================================

Result Rank        : #5
Paper Index        : 898
Similarity Score   : 0.4945

Title:
Semantic Vector Machines

Abstract Preview:
  We first present our work in machine translation, during which we used
aligned sentences to train a neural network to embed n-grams of different
languages into an $d$-dimensional space, such that n-grams that are the
translation of each other are close with respect to some metric. Good n-grams
to n-grams translation results were achieved, but full sentences translation is
still problematic. We realized that learning semantics of sentences and
documents was the key for solving a lot of natural

Summary:
We use a neural network to embed n-grams of different languages into an $d$-dimensional space. We then use the same network to learn the semantics of sentences. The result is an efficient and powerful way of embedding n- grammars.

Keywords:
embeddings words sentences
learning embeddings words
neural language models
sentence compression
embeddings words

# **Here NLP concludes!!!**