## 🌟 STEP 0 - Load & format the dataset and save the "abstracts_x(i.e no. of rows).csv" file

In [ ]:
#   !pip install datasets

In [ ]:
from datasets import load_dataset

### → Change values here

In [ ]:
# ==========================
# CONFIGURATION
# ==========================

NUM_PAPERS = 5000
SEED = 42

output_ABSTRACTS_csv = f"abstracts_{NUM_PAPERS}.csv"
input_ABSTRACTS_csv = f"abstracts_{NUM_PAPERS}.csv"

output_ANNOTATIONS_json = f"auto_annotations_{NUM_PAPERS}.json"
# input_ANNOTATIONS_json = f"auto_annotations_{NUM_PAPERS}.json"

# output_GOLD_json = f"gold_annotations_{NUM_PAPERS}.json"
# input_GOLD_json = f"gold_annotations_{NUM_PAPERS}.json"

# output_NORMALIZED_GOLD_json = f"normalized_gold_annotations_{NUM_PAPERS}.json"
# input_NORMALIZED_GOLD_json = f"normalized_gold_annotations_{NUM_PAPERS}.json"

# output_BIO_json = f"bio_dataset_{NUM_PAPERS}.json"
# input_BIO_json = f"bio_dataset_{NUM_PAPERS}.json"

API_KEY = "Your API"

BATCH_SIZE = 2

START_FROM = 0
# Allows the annotation process to resume from the last processed abstract (index) if it gets interrupted

SAVE_EVERY = 10
# Saves the annotations to a JSON file after every N abstracts to minimize data loss

SLEEP_TIME = 6
# Waits x seconds between Gemini API requests to avoid rate limit errors

ERROR_SLEEP_TIME = 20

MODEL_NAME = "gemini-3.1-flash-lite"

In [ ]:
print(f"Total Papers : {NUM_PAPERS}\n")
print(f"Output abstracts file : {output_ABSTRACTS_csv}")
print(f"Input abstracts file : {input_ABSTRACTS_csv}\n")
print(f"Output annotations file : {output_ANNOTATIONS_json}")
print(f"Input annotations file : {input_ANNOTATIONS_json}\n")
print(f"Output gold file : {output_GOLD_json}")
print(f"Input gold file : {input_GOLD_json}\n")
print(f"Output normalized gold file : {output_NORMALIZED_GOLD_json}")
print(f"Input normalized gold file : {input_NORMALIZED_GOLD_json}\n")
print(f"Output bio file : {output_BIO_json}")
print(f"Input bio file : {input_BIO_json}")

Total Papers : 1430

Output abstracts file : abstracts_1430.csv
Input abstracts file : abstracts_1430.csv

Output annotations file : auto_annotations_1430.json
Input annotations file : auto_annotations_1430.json

Output gold file : gold_annotations_1430.json
Input gold file : gold_annotations_1430.json

Output normalized gold file : normalized_gold_annotations_1430.json
Input normalized gold file : normalized_gold_annotations_1430.json

Output bio file : bio_dataset_1430.json
Input bio file : bio_dataset_1430.json

In [ ]:
# LOAD DATASET
dataset = load_dataset("CShorten/ML-ArXiv-Papers" , split = 'train')
print(f"Total Papers : {len(dataset)}")

README.md:   0%|          | 0.00/986 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

ML-Arxiv-Papers.csv:   0%|          | 0.00/147M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/117592 [00:00<?, ? examples/s]

Total Papers : 117592

In [ ]:
print(dataset)

NameError: name 'dataset' is not defined

In [ ]:
dataset[50]

{'Unnamed: 0.1': 50,
 'Unnamed: 0': 50.0,
 'title': 'Consistency of trace norm minimization',
 'abstract': '  Regularization by the sum of singular values, also referred to as the trace\nnorm, is a popular technique for estimating low rank rectangular matrices. In\nthis paper, we extend some of the consistency results of the Lasso to provide\nnecessary and sufficient conditions for rank consistency of trace norm\nminimization with the square loss. We also provide an adaptive version that is\nrank consistent even when the necessary condition for the non adaptive version\nis not fulfilled.\n'}

In [ ]:
# Shuffle dataset
dataset = dataset.shuffle(seed = SEED)

In [ ]:
# Select required number of papers
dataset_subset = dataset.select(range(NUM_PAPERS))

In [ ]:
print(f"Selected Papers : {len(dataset_subset)}")

Selected Papers : 5000

In [ ]:
import pandas as pd

In [ ]:
# Convert to DataFrame
df = dataset_subset.to_pandas()

In [ ]:
# Remove unwanted columns
df = df.drop(columns = ["Unnamed: 0", "Unnamed: 0.1"])

In [ ]:
# Remove leading/trailing spaces
df["title"] = df["title"].str.strip()
df["abstract"] = df["abstract"].str.strip()

# Replace multiple whitespaces/newlines/tabs with single space
df["title"] = df["title"].str.replace(r"\s+", " ", regex=True)
df["abstract"] = df["abstract"].str.replace(r"\s+", " ", regex=True)

In [ ]:
df.head()

NameError: name 'df' is not defined

In [ ]:
# Save the abstract CSV file
df.to_csv(
  output_ABSTRACTS_csv,
  index=True,
  index_label="id"
)

print(f"{output_ABSTRACTS_csv} saved successfully!")

abstracts_1430.csv saved successfully!


### Pipeline

```
STEP 1  Install Libraries
STEP 2  Imports
STEP 3  Gemini API
STEP 4  Configuration (Sirf yahan filename change karna)
STEP 5  Load CSV
STEP 6  Auto Annotation
STEP 7  Save JSON
STEP 8  Clean Dataset (Bad entities + Canonical Mapping)
STEP 9  Manual Review (Optional)
STEP 10 Gold Dataset Save
STEP 11 BIO Conversion
STEP 12 Train SciBERT
STEP 13 Evaluation
STEP 14 Save Model
STEP 15 Inference
```

## 🌟 STEP 1 - Perform the annotation and save the "auto_annotations_x(i.e no. of rows).json"

### → Change values here

In [ ]:
# ==========================
# CONFIGURATION
# ==========================

input_ABSTRACTS_csv = "abstracts_5000.csv"
output_ANNOTATIONS_json = f"auto_annotations_{NUM_PAPERS}.json"

MODEL_NAME = "gemini-3.1-flash-lite"

### 1.1. Install Libraries

In [ ]:
# !pip -q install -U google-genai
# !pip -q install datasets
# !pip -q install transformers
# !pip -q install seqeval
# !pip -q install accelerate

### 1.2. Import Required Libraries

In [ ]:
import os
import json
import time
import pandas as pd

from google import genai
from google.genai import types

from tqdm import tqdm

### 1.3. Gemini API

In [ ]:
# API_KEY = "Your  API"

client = genai.Client(api_key = API_KEY)

print("Gemini Connected Successfully!")

Gemini Connected Successfully!

### → Change values here

In [ ]:
BATCH_SIZE = 2

START_FROM = 0
# Allows the annotation process to resume from the last processed abstract (index) if it gets interrupted

SAVE_EVERY = 10
# Saves the annotations to a JSON file after every N abstracts to minimize data loss

SLEEP_TIME = 6
# Waits x seconds between Gemini API requests to avoid rate limit errors

ERROR_SLEEP_TIME = 20

print("Input File :", input_ABSTRACTS_csv)
print("Output File:", output_ANNOTATIONS_json)
print("Gemini Model:", MODEL_NAME)

Input File : abstracts_1430.csv
Output File: auto_annotations_1430.json
Gemini Model: gemini-2.5-flash-lite

### 1.4. Read the abstract (input) csv file

In [ ]:
df = pd.read_csv(input_ABSTRACTS_csv)

In [ ]:
df = df.dropna(subset = ["abstract"]).reset_index(drop = True)
# Removes rows with missing abstracts and resets the DataFrame index for clean sequential processing.

In [ ]:
print(f"Total Abstracts : {len(df)}")

Total Abstracts : 5000

In [ ]:
df.head()

,id,title,abstract
0,0,Epsilon Consistent Mixup: Structural Regulariz...,In this paper we propose $\epsilon$-Consistent...
1,1,Particle Graph Autoencoders and Differentiable...,Autoencoders have useful applications in high ...
2,2,Probabilistic DAG Search,Exciting contemporary machine learning problem...
3,3,Automatic Detection and Classification of Tick...,"Around the globe, ticks are the culprit of tra..."
4,4,Mixing Real and Synthetic Data to Enhance Neur...,Deep neural networks have gained tremendous im...

### 1.5. Define the "create_prompt()" function

In [ ]:
def create_prompt(text):

    return f"""
You are an expert scientific Named Entity Recognition (NER) annotator.

Your task is to identify and extract named entities from research paper abstracts.

Extract entities ONLY for the following four labels:

=========================================
ALGORITHM
=========================================

Definition:
Machine learning algorithms, deep learning models,
neural network architectures, statistical methods,
optimization algorithms, dimensionality reduction methods,
computational frameworks, foundation models,
large language models (LLMs), graph neural networks,
vision models, and diffusion models.

Examples:

Random Forest
Decision Tree
SVM
Support Vector Machine
XGBoost
LightGBM
CatBoost
CNN
Convolutional Neural Network
RNN
Recurrent Neural Network
LSTM
GRU
Transformer
BERT
RoBERTa
GPT
ResNet
VGG
AlexNet
U-Net
DeepONet
GAN
Autoencoder
PCA
SVD
POD
K-means
DBSCAN
Adam
SGD
AdaGrad
RMSProp


Do NOT label generic terms:

model
models
framework
frameworks
approach
approaches
method
methods
technique
techniques
system
systems
architecture
architectures
pipeline
strategy
procedure
mechanism
algorithm
algorithms
surrogate
emulation
reinforcement
sampling efficiency


=========================================
DATASET
=========================================

Definition:
Named datasets, benchmarks, corpora,
collections of samples, and evaluation datasets.

Examples:

ImageNet
CIFAR-10
CIFAR-100
MNIST
Fashion-MNIST
COCO
SQuAD
LibriSpeech
ASVspoof
KITTI
Cityscapes
Pascal VOC
UCI datasets
WikiText
MS MARCO
GLUE
SuperGLUE
Common Crawl
MIMIC-III
MIMIC-IV


Extract only explicitly named datasets.

Do NOT label generic dataset words:

dataset
datasets
training dataset
test dataset
benchmark
benchmarks
corpus
corpora
samples
training data
testing data


=========================================
TASK
=========================================

Definition:
The computational, machine learning,
or analytical problem being solved.

Examples:

Image Classification
Text Classification
Named Entity Recognition
Object Detection
Semantic Segmentation
Instance Segmentation
Speech Recognition
Speaker Verification
Language Identification
Machine Translation
Regression
Prediction
Feature Selection
Sentiment Analysis
Anomaly Detection
Clustering
Recommendation
Forecasting
Information Retrieval
Question Answering
Text Generation
Image Captioning
Machine Reading Comprehension
Knowledge Graph Completion
Link Prediction
Node Classification
Time Series Forecasting
Speech Enhancement
Face Recognition
Pose Estimation


Do NOT classify scientific domains,
application areas,
or research fields as TASK.

Examples NOT TASK:

healthcare
medicine
bioinformatics
computer vision
natural language processing
medical imaging
chemistry
combustion chemistry
physics
biology
finance
cybersecurity


Extract complete task names whenever possible.

Correct:
Image Classification

Incorrect:
Classification


Correct:
Object Detection

Incorrect:
Detection


=========================================
METRIC
=========================================

Definition:
Evaluation metrics used to measure model performance.

Examples:

Accuracy
Precision
Recall
F1-score
F1 score
BLEU
ROUGE
ROC-AUC
AUC
RMSE
MSE
MAE
MAPE
Specificity
Sensitivity
IoU
Dice coefficient
Mean Average Precision
WER
CER
PSNR
SSIM
NDCG
Hit Rate
Top-1 Accuracy
Top-5 Accuracy
Perplexity

Do NOT extract numerical values.

Correct:
Accuracy

Incorrect:
95% Accuracy

Incorrect:
0.92 F1


=========================================
STRICT RULES
=========================================

1. Extract ONLY explicitly mentioned entities from the abstract.

2. Do NOT infer or hallucinate entities.

3. Preserve the original entity text and capitalization.

4. Remove duplicate entity-label pairs. The same entity should appear only once within an abstract.

5. If multiple versions exist, return the longest complete entity.

Example:

Return:
Convolutional Neural Network

Do not return:
Neural Network


6. Every entity must belong to exactly one label.

7. Do NOT label generic words.

8. Do NOT label scientific domains as TASK.

9. Do NOT create entities that are not present in the abstract.

10. Do NOT return LaTeX notation, mathematical expressions,
or escape sequences inside entity names.

11. Convert mathematical notation into plain text whenever possible.

Examples:

Correct:
epsilon-Consistent Mixup

Incorrect:
LaTeX formatted entity names

Correct:
alpha

Incorrect:
Mathematical escape sequences

12. Return entity names as plain UTF-8 text only.

13. The output must be valid JSON and directly parseable using Python json.loads().

14. If no entities exist, return:

{{
    "entities":[]
}}

15. Return ONLY raw JSON.

16. Do NOT use markdown.

17. Do NOT use ```json blocks.

18. Do NOT provide explanations.

19. If a longer entity completely contains a shorter entity, return only the longer entity unless both are explicitly used as separate independent concepts in the abstract.

20. Do not return spelling variants of the same entity. Return only one canonical surface form exactly as it appears in the abstract.
=========================================
OUTPUT FORMAT
=========================================

{{
    "entities":[
        {{
            "entity":"entity text",
            "label":"ALGORITHM"
        }},
        {{
            "entity":"entity text",
            "label":"DATASET"
        }},
        {{
            "entity":"entity text",
            "label":"TASK"
        }},
        {{
            "entity":"entity text",
            "label":"METRIC"
        }}
    ]
}}


=========================================
ABSTRACT
=========================================

{text}
"""

In [ ]:
print(create_prompt("test abstract"))

You are an expert scientific Named Entity Recognition (NER) annotator.

Your task is to identify and extract named entities from research paper abstracts.

Extract entities ONLY for the following four labels:

=========================================
ALGORITHM
=========================================

Definition:
Machine learning algorithms, deep learning models,
neural network architectures, statistical methods,
optimization algorithms, dimensionality reduction methods,
computational frameworks, foundation models,
large language models (LLMs), graph neural networks,
vision models, and diffusion models.

Examples:

Random Forest
Decision Tree
SVM
Support Vector Machine
XGBoost
LightGBM
CatBoost
CNN
Convolutional Neural Network
RNN
Recurrent Neural Network
LSTM
GRU
Transformer
BERT
RoBERTa
GPT
ResNet
VGG
AlexNet
U-Net
DeepONet
GAN
Autoencoder
PCA
SVD
POD
K-means
DBSCAN
Adam
SGD
AdaGrad
RMSProp


Do NOT label generic terms:

model
models
framework
frameworks
approach
approaches
method
methods
technique
techniques
system
systems
architecture
architectures
pipeline
strategy
procedure
mechanism
algorithm
algorithms
surrogate
emulation
reinforcement
sampling efficiency


=========================================
DATASET
=========================================

Definition:
Named datasets, benchmarks, corpora,
collections of samples, and evaluation datasets.

Examples:

ImageNet
CIFAR-10
CIFAR-100
MNIST
Fashion-MNIST
COCO
SQuAD
LibriSpeech
ASVspoof
KITTI
Cityscapes
Pascal VOC
UCI datasets
WikiText
MS MARCO
GLUE
SuperGLUE
Common Crawl
MIMIC-III
MIMIC-IV


Extract only explicitly named datasets.

Do NOT label generic dataset words:

dataset
datasets
training dataset
test dataset
benchmark
benchmarks
corpus
corpora
samples
training data
testing data


=========================================
TASK
=========================================

Definition:
The computational, machine learning,
or analytical problem being solved.

Examples:

Image Classification
Text Classification
Named Entity Recognition
Object Detection
Semantic Segmentation
Instance Segmentation
Speech Recognition
Speaker Verification
Language Identification
Machine Translation
Regression
Prediction
Feature Selection
Sentiment Analysis
Anomaly Detection
Clustering
Recommendation
Forecasting
Information Retrieval
Question Answering
Text Generation
Image Captioning
Machine Reading Comprehension
Knowledge Graph Completion
Link Prediction
Node Classification
Time Series Forecasting
Speech Enhancement
Face Recognition
Pose Estimation


Do NOT classify scientific domains,
application areas,
or research fields as TASK.

Examples NOT TASK:

healthcare
medicine
bioinformatics
computer vision
natural language processing
medical imaging
chemistry
combustion chemistry
physics
biology
finance
cybersecurity


Extract complete task names whenever possible.

Correct:
Image Classification

Incorrect:
Classification


Correct:
Object Detection

Incorrect:
Detection


=========================================
METRIC
=========================================

Definition:
Evaluation metrics used to measure model performance.

Examples:

Accuracy
Precision
Recall
F1-score
F1 score
BLEU
ROUGE
ROC-AUC
AUC
RMSE
MSE
MAE
MAPE
Specificity
Sensitivity
IoU
Dice coefficient
Mean Average Precision
WER
CER
PSNR
SSIM
NDCG
Hit Rate
Top-1 Accuracy
Top-5 Accuracy
Perplexity

Do NOT extract numerical values.

Correct:
Accuracy

Incorrect:
95% Accuracy

Incorrect:
0.92 F1


=========================================
STRICT RULES
=========================================

1. Extract ONLY explicitly mentioned entities from the abstract.

2. Do NOT infer or hallucinate entities.

3. Preserve the original entity text and capitalization.

4. Remove duplicate entity-label pairs. The same entity should appear only once within an abstract.

5. If multiple versions exist, return the longest complete entity.

Example:

Return:
Convolutional Neural Network

Do not return:
Neural Network


6. Every entity must belong to exactly one label.

7. Do NOT label generic words.

8. Do NOT label scientific domains as TASK.

9. Do NOT create entities that are not present in the abstract.

10. Do NOT return LaTeX notation, mathematical expressions,
or escape sequences inside entity names.

11. Convert mathematical notation into plain text whenever possible.

Examples:

Correct:
epsilon-Consistent Mixup

Incorrect:
LaTeX formatted entity names

Correct:
alpha

Incorrect:
Mathematical escape sequences

12. Return entity names as plain UTF-8 text only.

13. The output must be valid JSON and directly parseable using Python json.loads().

14. If no entities exist, return:

{
    "entities":[]
}

15. Return ONLY raw JSON.

16. Do NOT use markdown.

17. Do NOT use ```json blocks.

18. Do NOT provide explanations.

19. If a longer entity completely contains a shorter entity, return only the longer entity unless both are explicitly used as separate independent concepts in the abstract.

20. Do not return spelling variants of the same entity. Return only one canonical surface form exactly as it appears in the abstract.
=========================================
OUTPUT FORMAT
=========================================

{
    "entities":[
        {
            "entity":"entity text",
            "label":"ALGORITHM"
        },
        {
            "entity":"entity text",
            "label":"DATASET"
        },
        {
            "entity":"entity text",
            "label":"TASK"
        },
        {
            "entity":"entity text",
            "label":"METRIC"
        }
    ]
}


=========================================
ABSTRACT
=========================================

test abstract

#### 1.5.1. Define the "create_batch_prompt()" function

In [ ]:
def create_batch_prompt(batch):

    abstracts = ""

    for i, paper in enumerate(batch, start=1):

        abstracts += f"""

=========================================
ABSTRACT {i}
=========================================

{paper["abstract"]}

"""

    batch_instruction = f"""

IMPORTANT

The text above contains {len(batch)} COMPLETELY INDEPENDENT research paper abstracts.

Treat each abstract independently.

Never transfer entities from one abstract to another.

Do NOT merge entities from different abstracts.

An entity appearing in ABSTRACT 1 must NOT appear in the output of ABSTRACT 2 unless it is explicitly present in ABSTRACT 2.

Process each abstract from scratch.

Return ONLY a JSON ARRAY.

Every JSON object must contain exactly one key named "entities".

Do not add any other keys such as "abstract", "id", "title", "index", "confidence", "reasoning", or "notes".

The response MUST begin with '[' and end with ']'.

Do not include any text before or after the JSON array.

The array MUST contain exactly {len(batch)} objects.

Object i corresponds to ABSTRACT i.

The order of JSON objects MUST exactly match the order of the input abstracts.

Each object MUST follow exactly this structure:

{{
    "entities":[
        {{
            "entity":"entity text",
            "label":"ALGORITHM"
        }}
    ]
}}

If an abstract contains no entities, return:

{{
    "entities":[]
}}

Return ONLY the JSON array.

Do NOT use markdown.

Do NOT provide explanations.

Do NOT omit any abstract.

The output must be directly parseable using Python json.loads().

Return EXACTLY one JSON object for every abstract.

If there are 2 abstracts,
return exactly 2 objects.

If there are 5 abstracts,
return exactly 5 objects.

Never return fewer objects.

Never return more objects.

Within each abstract, remove duplicate entities before returning the JSON.

Each abstract is an independent annotation task.

Ignore all previous and following abstracts while extracting entities.
"""

    return create_prompt(abstracts + batch_instruction)

In [ ]:
batch = df.head(2).to_dict("records")

prompt = create_batch_prompt(batch)
print(prompt)
print("\nLength of Prompt :",len(prompt))

You are an expert scientific Named Entity Recognition (NER) annotator.

Your task is to identify and extract named entities from research paper abstracts.

Extract entities ONLY for the following four labels:

=========================================
ALGORITHM
=========================================

Definition:
Machine learning algorithms, deep learning models,
neural network architectures, statistical methods,
optimization algorithms, dimensionality reduction methods,
computational frameworks, foundation models,
large language models (LLMs), graph neural networks,
vision models, and diffusion models.

Examples:

Random Forest
Decision Tree
SVM
Support Vector Machine
XGBoost
LightGBM
CatBoost
CNN
Convolutional Neural Network
RNN
Recurrent Neural Network
LSTM
GRU
Transformer
BERT
RoBERTa
GPT
ResNet
VGG
AlexNet
U-Net
DeepONet
GAN
Autoencoder
PCA
SVD
POD
K-means
DBSCAN
Adam
SGD
AdaGrad
RMSProp


Do NOT label generic terms:

model
models
framework
frameworks
approach
approaches
method
methods
technique
techniques
system
systems
architecture
architectures
pipeline
strategy
procedure
mechanism
algorithm
algorithms
surrogate
emulation
reinforcement
sampling efficiency


=========================================
DATASET
=========================================

Definition:
Named datasets, benchmarks, corpora,
collections of samples, and evaluation datasets.

Examples:

ImageNet
CIFAR-10
CIFAR-100
MNIST
Fashion-MNIST
COCO
SQuAD
LibriSpeech
ASVspoof
KITTI
Cityscapes
Pascal VOC
UCI datasets
WikiText
MS MARCO
GLUE
SuperGLUE
Common Crawl
MIMIC-III
MIMIC-IV


Extract only explicitly named datasets.

Do NOT label generic dataset words:

dataset
datasets
training dataset
test dataset
benchmark
benchmarks
corpus
corpora
samples
training data
testing data


=========================================
TASK
=========================================

Definition:
The computational, machine learning,
or analytical problem being solved.

Examples:

Image Classification
Text Classification
Named Entity Recognition
Object Detection
Semantic Segmentation
Instance Segmentation
Speech Recognition
Speaker Verification
Language Identification
Machine Translation
Regression
Prediction
Feature Selection
Sentiment Analysis
Anomaly Detection
Clustering
Recommendation
Forecasting
Information Retrieval
Question Answering
Text Generation
Image Captioning
Machine Reading Comprehension
Knowledge Graph Completion
Link Prediction
Node Classification
Time Series Forecasting
Speech Enhancement
Face Recognition
Pose Estimation


Do NOT classify scientific domains,
application areas,
or research fields as TASK.

Examples NOT TASK:

healthcare
medicine
bioinformatics
computer vision
natural language processing
medical imaging
chemistry
combustion chemistry
physics
biology
finance
cybersecurity


Extract complete task names whenever possible.

Correct:
Image Classification

Incorrect:
Classification


Correct:
Object Detection

Incorrect:
Detection


=========================================
METRIC
=========================================

Definition:
Evaluation metrics used to measure model performance.

Examples:

Accuracy
Precision
Recall
F1-score
F1 score
BLEU
ROUGE
ROC-AUC
AUC
RMSE
MSE
MAE
MAPE
Specificity
Sensitivity
IoU
Dice coefficient
Mean Average Precision
WER
CER
PSNR
SSIM
NDCG
Hit Rate
Top-1 Accuracy
Top-5 Accuracy
Perplexity

Do NOT extract numerical values.

Correct:
Accuracy

Incorrect:
95% Accuracy

Incorrect:
0.92 F1


=========================================
STRICT RULES
=========================================

1. Extract ONLY explicitly mentioned entities from the abstract.

2. Do NOT infer or hallucinate entities.

3. Preserve the original entity text and capitalization.

4. Remove duplicate entity-label pairs. The same entity should appear only once within an abstract.

5. If multiple versions exist, return the longest complete entity.

Example:

Return:
Convolutional Neural Network

Do not return:
Neural Network


6. Every entity must belong to exactly one label.

7. Do NOT label generic words.

8. Do NOT label scientific domains as TASK.

9. Do NOT create entities that are not present in the abstract.

10. Do NOT return LaTeX notation, mathematical expressions,
or escape sequences inside entity names.

11. Convert mathematical notation into plain text whenever possible.

Examples:

Correct:
epsilon-Consistent Mixup

Incorrect:
LaTeX formatted entity names

Correct:
alpha

Incorrect:
Mathematical escape sequences

12. Return entity names as plain UTF-8 text only.

13. The output must be valid JSON and directly parseable using Python json.loads().

14. If no entities exist, return:

{
    "entities":[]
}

15. Return ONLY raw JSON.

16. Do NOT use markdown.

17. Do NOT use ```json blocks.

18. Do NOT provide explanations.

19. If a longer entity completely contains a shorter entity, return only the longer entity unless both are explicitly used as separate independent concepts in the abstract.

20. Do not return spelling variants of the same entity. Return only one canonical surface form exactly as it appears in the abstract.
=========================================
OUTPUT FORMAT
=========================================

{
    "entities":[
        {
            "entity":"entity text",
            "label":"ALGORITHM"
        },
        {
            "entity":"entity text",
            "label":"DATASET"
        },
        {
            "entity":"entity text",
            "label":"TASK"
        },
        {
            "entity":"entity text",
            "label":"METRIC"
        }
    ]
}


=========================================
ABSTRACT
=========================================



=========================================
ABSTRACT 1
=========================================

In this paper we propose $\epsilon$-Consistent Mixup ($\epsilon$mu). $\epsilon$mu is a data-based structural regularization technique that combines Mixup's linear interpolation with consistency regularization in the Mixup direction, by compelling a simple adaptive tradeoff between the two. This learnable combination of consistency and interpolation induces a more flexible structure on the evolution of the response across the feature space and is shown to improve semi-supervised classification accuracy on the SVHN and CIFAR10 benchmark datasets, yielding the largest gains in the most challenging low label-availability scenarios. Empirical studies comparing $\epsilon$mu and Mixup are presented and provide insight into the mechanisms behind $\epsilon$mu's effectiveness. In particular, $\epsilon$mu is found to produce more accurate synthetic labels and more confident predictions than Mixup.



=========================================
ABSTRACT 2
=========================================

Autoencoders have useful applications in high energy physics in anomaly detection, particularly for jets - collimated showers of particles produced in collisions such as those at the CERN Large Hadron Collider. We explore the use of graph-based autoencoders, which operate on jets in their "particle cloud" representations and can leverage the interdependencies among the particles within a jet, for such tasks. Additionally, we develop a differentiable approximation to the energy mover's distance via a graph neural network, which may subsequently be used as a reconstruction loss function for autoencoders.



IMPORTANT

The text above contains 2 COMPLETELY INDEPENDENT research paper abstracts.

Treat each abstract independently.

Never transfer entities from one abstract to another.

Do NOT merge entities from different abstracts.

An entity appearing in ABSTRACT 1 must NOT appear in the output of ABSTRACT 2 unless it is explicitly present in ABSTRACT 2.

Process each abstract from scratch.

Return ONLY a JSON ARRAY.

Every JSON object must contain exactly one key named "entities".

Do not add any other keys such as "abstract", "id", "title", "index", "confidence", "reasoning", or "notes".

The response MUST begin with '[' and end with ']'.

Do not include any text before or after the JSON array.

The array MUST contain exactly 2 objects.

Object i corresponds to ABSTRACT i.

The order of JSON objects MUST exactly match the order of the input abstracts.

Each object MUST follow exactly this structure:

{
    "entities":[
        {
            "entity":"entity text",
            "label":"ALGORITHM"
        }
    ]
}

If an abstract contains no entities, return:

{
    "entities":[]
}

Return ONLY the JSON array.

Do NOT use markdown.

Do NOT provide explanations.

Do NOT omit any abstract.

The output must be directly parseable using Python json.loads().

Return EXACTLY one JSON object for every abstract.

If there are 2 abstracts,
return exactly 2 objects.

If there are 5 abstracts,
return exactly 5 objects.

Never return fewer objects.

Never return more objects.

Within each abstract, remove duplicate entities before returning the JSON.

Each abstract is an independent annotation task.

Ignore all previous and following abstracts while extracting entities.



Length of Prompt : 9061

### 1.6. Define the "annotate_batch()" function

In [ ]:
def annotate_batch(batch):

    prompt = create_batch_prompt(batch)

    response = client.models.generate_content(
        model=MODEL_NAME,
        contents=prompt
    )

    text = response.text.strip()

    text = text.replace("```json", "").replace("```", "").strip()

    return json.loads(text)

#### 1.6.1. Test on first 20 papers

In [ ]:
test_df = df.head(20).copy()
list_of_dict_papers_20 = test_df.to_dict("records")

print("Total Papers:", len(list_of_dict_papers_20))

In [ ]:
annotations = []

for i in range(0, len(list_of_dict_papers_20), BATCH_SIZE):

    batch = list_of_dict_papers_20[i:i + BATCH_SIZE]

    print(f"Processing Paper No. {i + 1} - {i + len(batch)}")

    try:

        result = annotate_batch(batch)

        for paper, ann in zip(batch, result):

            annotations.append({
                "id": paper["id"],
                "title": paper["title"],
                "annotation": json.dumps(ann, ensure_ascii=False)
            })

        time.sleep(3)

    except Exception as e:

        print(e)
        break

print("\nDone")
print(f"Annotated {len(annotations)} papers")

Processing 1 - 2
Processing 3 - 4
Processing 5 - 6
Processing 7 - 8
Processing 9 - 10
Processing 11 - 12
Processing 13 - 14
Processing 15 - 16
Processing 17 - 18
Processing 19 - 20

Done
Annotated: 20

In [ ]:
OUTPUT_test_JSON = "test_auto_annotations_20.json"

with open(OUTPUT_test_JSON, "w", encoding="utf-8") as f:
    json.dump(annotations, f, indent=2, ensure_ascii=False)

print("Saved:", OUTPUT_test_JSON)

Saved: auto_annotations_20.json

In [ ]:
for item in annotations[:5]:
    print("ID:", item["id"])
    print("Title:", item["title"])
    print(json.loads(item["annotation"]))
    print("\n")

ID: 0
Title: Epsilon Consistent Mixup: Structural Regularization with an Adaptive Consistency-Interpolation Tradeoff
{'entities': [{'entity': 'epsilon-Consistent Mixup', 'label': 'ALGORITHM'}, {'entity': 'Mixup', 'label': 'ALGORITHM'}, {'entity': 'SVHN', 'label': 'DATASET'}, {'entity': 'CIFAR10', 'label': 'DATASET'}, {'entity': 'semi-supervised classification', 'label': 'TASK'}, {'entity': 'accuracy', 'label': 'METRIC'}]}


ID: 1
Title: Particle Graph Autoencoders and Differentiable, Learned Energy Mover's Distance
{'entities': [{'entity': 'Autoencoders', 'label': 'ALGORITHM'}, {'entity': 'graph-based autoencoders', 'label': 'ALGORITHM'}, {'entity': 'graph neural network', 'label': 'ALGORITHM'}, {'entity': 'CERN Large Hadron Collider', 'label': 'DATASET'}, {'entity': 'anomaly detection', 'label': 'TASK'}]}


ID: 2
Title: Probabilistic DAG Search
{'entities': [{'entity': 'Gaussian models', 'label': 'ALGORITHM'}, {'entity': 'Tic-Tac-Toe', 'label': 'DATASET'}, {'entity': 'feature selection', 'label': 'TASK'}]}


ID: 3
Title: Automatic Detection and Classification of Tick-borne Skin Lesions using Deep Learning
{'entities': [{'entity': 'convolutional neural network', 'label': 'ALGORITHM'}, {'entity': 'ResNet 34', 'label': 'ALGORITHM'}, {'entity': 'ResNet 50', 'label': 'ALGORITHM'}, {'entity': 'VGG 19', 'label': 'ALGORITHM'}, {'entity': 'Dense Net 121', 'label': 'ALGORITHM'}, {'entity': 'DenseNet 121', 'label': 'ALGORITHM'}, {'entity': 'skin lesion detection', 'label': 'TASK'}, {'entity': 'Accuracy', 'label': 'METRIC'}]}


ID: 4
Title: Mixing Real and Synthetic Data to Enhance Neural Network Training -- A Review of Current Approaches
{'entities': [{'entity': 'Deep neural networks', 'label': 'ALGORITHM'}]}

### 1.7. Annote the "abstracts_x(i.e no. of rows).csv" file

In [ ]:
list_of_dict_papers = df.head(NUM_PAPERS).to_dict("records")

In [ ]:
if os.path.exists(output_ANNOTATIONS_json):

    with open(output_ANNOTATIONS_json, "r", encoding="utf-8") as f:
        annotations = json.load(f)

    START_FROM = len(annotations)

    print(f"Resuming from Paper {START_FROM}")

else:

    annotations = []
    START_FROM = 0

    print("Starting Fresh")

Resuming from Paper 2428

In [ ]:
for i in range(START_FROM, len(list_of_dict_papers), BATCH_SIZE):

    batch = list_of_dict_papers[i:i+BATCH_SIZE]

    print(f"\nProcessing Papers {i+1} - {i+len(batch)}")


    try:

        result = annotate_batch(batch)


        for paper, ann in zip(batch, result):

            annotations.append({

                "id": paper["id"],

                "title": paper["title"],

                "abstract": paper["abstract"],

                "annotation": json.dumps(
                    ann,
                    ensure_ascii=False
                )

            })


        # Save periodically
        if len(annotations) % SAVE_EVERY == 0:


            with open(output_ANNOTATIONS_json, "w", encoding="utf-8") as f:

                json.dump(
                    annotations,
                    f,
                    indent=2,
                    ensure_ascii=False
                )


            print("Progress Saved")


        time.sleep(SLEEP_TIME)



    except Exception as e:


        print("Error:", e)


        with open(output_ANNOTATIONS_json, "w", encoding="utf-8") as f:

            json.dump(
                annotations,
                f,
                indent=2,
                ensure_ascii=False
            )


        print("Emergency Save Done")


        time.sleep(ERROR_SLEEP_TIME)

        break

Processing Papers 2429 - 2430
Progress Saved

Processing Papers 2431 - 2432

Processing Papers 2433 - 2434

Processing Papers 2435 - 2436

Processing Papers 2437 - 2438

Processing Papers 2439 - 2440
Progress Saved

Processing Papers 2441 - 2442

Processing Papers 2443 - 2444

Processing Papers 2445 - 2446

Processing Papers 2447 - 2448

Processing Papers 2449 - 2450
Progress Saved

Processing Papers 2451 - 2452

Processing Papers 2453 - 2454

Processing Papers 2455 - 2456

Processing Papers 2457 - 2458

Processing Papers 2459 - 2460
Progress Saved

Processing Papers 2461 - 2462

Processing Papers 2463 - 2464

Processing Papers 2465 - 2466

Processing Papers 2467 - 2468

Processing Papers 2469 - 2470
Progress Saved

Processing Papers 2471 - 2472

Processing Papers 2473 - 2474

Processing Papers 2475 - 2476

Processing Papers 2477 - 2478

Processing Papers 2479 - 2480
Progress Saved

Processing Papers 2481 - 2482

Processing Papers 2483 - 2484

Processing Papers 2485 - 2486

Processing Papers 2487 - 2488

Processing Papers 2489 - 2490
Progress Saved

Processing Papers 2491 - 2492

Processing Papers 2493 - 2494

Processing Papers 2495 - 2496

Processing Papers 2497 - 2498

Processing Papers 2499 - 2500
Progress Saved

Processing Papers 2501 - 2502

Processing Papers 2503 - 2504

Processing Papers 2505 - 2506

Processing Papers 2507 - 2508

Processing Papers 2509 - 2510
Progress Saved

Processing Papers 2511 - 2512

Processing Papers 2513 - 2514

Processing Papers 2515 - 2516

Processing Papers 2517 - 2518

Processing Papers 2519 - 2520
Progress Saved

Processing Papers 2521 - 2522

Processing Papers 2523 - 2524

Processing Papers 2525 - 2526

Processing Papers 2527 - 2528

Processing Papers 2529 - 2530
Progress Saved

Processing Papers 2531 - 2532

Processing Papers 2533 - 2534

Processing Papers 2535 - 2536

Processing Papers 2537 - 2538

Processing Papers 2539 - 2540
Progress Saved

Processing Papers 2541 - 2542

Processing Papers 2543 - 2544

Processing Papers 2545 - 2546

Processing Papers 2547 - 2548

Processing Papers 2549 - 2550
Progress Saved

Processing Papers 2551 - 2552

Processing Papers 2553 - 2554

Processing Papers 2555 - 2556

Processing Papers 2557 - 2558

Processing Papers 2559 - 2560
Progress Saved

Processing Papers 2561 - 2562

Processing Papers 2563 - 2564

Processing Papers 2565 - 2566

Processing Papers 2567 - 2568

Processing Papers 2569 - 2570
Progress Saved

Processing Papers 2571 - 2572

Processing Papers 2573 - 2574

Processing Papers 2575 - 2576

Processing Papers 2577 - 2578

Processing Papers 2579 - 2580
Progress Saved

Processing Papers 2581 - 2582

Processing Papers 2583 - 2584

Processing Papers 2585 - 2586

Processing Papers 2587 - 2588

Processing Papers 2589 - 2590
Progress Saved

Processing Papers 2591 - 2592

Processing Papers 2593 - 2594

Processing Papers 2595 - 2596

Processing Papers 2597 - 2598

Processing Papers 2599 - 2600
Progress Saved

Processing Papers 2601 - 2602

Processing Papers 2603 - 2604

Processing Papers 2605 - 2606

Processing Papers 2607 - 2608

Processing Papers 2609 - 2610
Progress Saved

Processing Papers 2611 - 2612

Processing Papers 2613 - 2614

Processing Papers 2615 - 2616

Processing Papers 2617 - 2618

Processing Papers 2619 - 2620
Progress Saved

Processing Papers 2621 - 2622

Processing Papers 2623 - 2624

Processing Papers 2625 - 2626

Processing Papers 2627 - 2628

Processing Papers 2629 - 2630
Progress Saved

Processing Papers 2631 - 2632

Processing Papers 2633 - 2634

Processing Papers 2635 - 2636

Processing Papers 2637 - 2638

Processing Papers 2639 - 2640
Progress Saved

Processing Papers 2641 - 2642

Processing Papers 2643 - 2644

Processing Papers 2645 - 2646

Processing Papers 2647 - 2648

Processing Papers 2649 - 2650
Progress Saved

Processing Papers 2651 - 2652

Processing Papers 2653 - 2654

Processing Papers 2655 - 2656

Processing Papers 2657 - 2658

Processing Papers 2659 - 2660
Progress Saved

Processing Papers 2661 - 2662

Processing Papers 2663 - 2664

Processing Papers 2665 - 2666

Processing Papers 2667 - 2668

Processing Papers 2669 - 2670
Progress Saved

Processing Papers 2671 - 2672

Processing Papers 2673 - 2674

Processing Papers 2675 - 2676

Processing Papers 2677 - 2678

Processing Papers 2679 - 2680
Progress Saved

Processing Papers 2681 - 2682

Processing Papers 2683 - 2684

Processing Papers 2685 - 2686

Processing Papers 2687 - 2688

Processing Papers 2689 - 2690
Progress Saved

Processing Papers 2691 - 2692

Processing Papers 2693 - 2694

Processing Papers 2695 - 2696

Processing Papers 2697 - 2698

Processing Papers 2699 - 2700
Progress Saved

Processing Papers 2701 - 2702

Processing Papers 2703 - 2704

Processing Papers 2705 - 2706

Processing Papers 2707 - 2708

Processing Papers 2709 - 2710
Progress Saved

Processing Papers 2711 - 2712

Processing Papers 2713 - 2714

Processing Papers 2715 - 2716

Processing Papers 2717 - 2718

Processing Papers 2719 - 2720
Progress Saved

Processing Papers 2721 - 2722

Processing Papers 2723 - 2724

Processing Papers 2725 - 2726

Processing Papers 2727 - 2728

Processing Papers 2729 - 2730
Progress Saved

Processing Papers 2731 - 2732

Processing Papers 2733 - 2734

Processing Papers 2735 - 2736

Processing Papers 2737 - 2738

Processing Papers 2739 - 2740
Progress Saved

Processing Papers 2741 - 2742

Processing Papers 2743 - 2744

Processing Papers 2745 - 2746

Processing Papers 2747 - 2748

Processing Papers 2749 - 2750
Progress Saved

Processing Papers 2751 - 2752

Processing Papers 2753 - 2754

Processing Papers 2755 - 2756

Processing Papers 2757 - 2758

Processing Papers 2759 - 2760
Progress Saved

Processing Papers 2761 - 2762

Processing Papers 2763 - 2764

Processing Papers 2765 - 2766

Processing Papers 2767 - 2768

Processing Papers 2769 - 2770
Progress Saved

Processing Papers 2771 - 2772

Processing Papers 2773 - 2774

Processing Papers 2775 - 2776

Processing Papers 2777 - 2778

Processing Papers 2779 - 2780
Progress Saved

Processing Papers 2781 - 2782

Processing Papers 2783 - 2784

Processing Papers 2785 - 2786

Processing Papers 2787 - 2788

Processing Papers 2789 - 2790
Progress Saved

Processing Papers 2791 - 2792

Processing Papers 2793 - 2794

Processing Papers 2795 - 2796

Processing Papers 2797 - 2798

Processing Papers 2799 - 2800
Progress Saved

Processing Papers 2801 - 2802

Processing Papers 2803 - 2804

Processing Papers 2805 - 2806

Processing Papers 2807 - 2808

Processing Papers 2809 - 2810
Progress Saved

Processing Papers 2811 - 2812

Processing Papers 2813 - 2814

Processing Papers 2815 - 2816

Processing Papers 2817 - 2818

Processing Papers 2819 - 2820
Progress Saved

Processing Papers 2821 - 2822

Processing Papers 2823 - 2824

Processing Papers 2825 - 2826

Processing Papers 2827 - 2828

Processing Papers 2829 - 2830
Progress Saved

Processing Papers 2831 - 2832

Processing Papers 2833 - 2834

Processing Papers 2835 - 2836

Processing Papers 2837 - 2838

Processing Papers 2839 - 2840
Progress Saved

Processing Papers 2841 - 2842

Processing Papers 2843 - 2844

Processing Papers 2845 - 2846

Processing Papers 2847 - 2848

Processing Papers 2849 - 2850
Progress Saved

Processing Papers 2851 - 2852

Processing Papers 2853 - 2854

Processing Papers 2855 - 2856

Processing Papers 2857 - 2858

Processing Papers 2859 - 2860
Progress Saved

Processing Papers 2861 - 2862

Processing Papers 2863 - 2864

Processing Papers 2865 - 2866

Processing Papers 2867 - 2868

Processing Papers 2869 - 2870
Progress Saved

Processing Papers 2871 - 2872

Processing Papers 2873 - 2874

Processing Papers 2875 - 2876

Processing Papers 2877 - 2878

Processing Papers 2879 - 2880
Progress Saved

Processing Papers 2881 - 2882

Processing Papers 2883 - 2884

Processing Papers 2885 - 2886

Processing Papers 2887 - 2888

Processing Papers 2889 - 2890
Progress Saved

Processing Papers 2891 - 2892

Processing Papers 2893 - 2894

Processing Papers 2895 - 2896

Processing Papers 2897 - 2898

Processing Papers 2899 - 2900
Progress Saved

Processing Papers 2901 - 2902

Processing Papers 2903 - 2904

Processing Papers 2905 - 2906

Processing Papers 2907 - 2908

Processing Papers 2909 - 2910
Progress Saved

Processing Papers 2911 - 2912

Processing Papers 2913 - 2914

Processing Papers 2915 - 2916

Processing Papers 2917 - 2918

Processing Papers 2919 - 2920
Progress Saved

Processing Papers 2921 - 2922

Processing Papers 2923 - 2924

Processing Papers 2925 - 2926

Processing Papers 2927 - 2928

Processing Papers 2929 - 2930
Progress Saved

Processing Papers 2931 - 2932

Processing Papers 2933 - 2934

Processing Papers 2935 - 2936

Processing Papers 2937 - 2938

Processing Papers 2939 - 2940
Progress Saved

Processing Papers 2941 - 2942

Processing Papers 2943 - 2944

Processing Papers 2945 - 2946

Processing Papers 2947 - 2948

Processing Papers 2949 - 2950
Progress Saved

Processing Papers 2951 - 2952

Processing Papers 2953 - 2954

Processing Papers 2955 - 2956

Processing Papers 2957 - 2958

Processing Papers 2959 - 2960
Progress Saved

Processing Papers 2961 - 2962

Processing Papers 2963 - 2964

Processing Papers 2965 - 2966

Processing Papers 2967 - 2968

Processing Papers 2969 - 2970
Progress Saved

Processing Papers 2971 - 2972

Processing Papers 2973 - 2974

Processing Papers 2975 - 2976

Processing Papers 2977 - 2978

Processing Papers 2979 - 2980
Progress Saved

Processing Papers 2981 - 2982

Processing Papers 2983 - 2984

Processing Papers 2985 - 2986

Processing Papers 2987 - 2988

Processing Papers 2989 - 2990
Progress Saved

Processing Papers 2991 - 2992

Processing Papers 2993 - 2994

Processing Papers 2995 - 2996

Processing Papers 2997 - 2998

Processing Papers 2999 - 3000
Progress Saved

Processing Papers 3001 - 3002

Processing Papers 3003 - 3004

Processing Papers 3005 - 3006

Processing Papers 3007 - 3008

Processing Papers 3009 - 3010
Progress Saved

Processing Papers 3011 - 3012

Processing Papers 3013 - 3014

Processing Papers 3015 - 3016

Processing Papers 3017 - 3018

Processing Papers 3019 - 3020
Progress Saved

Processing Papers 3021 - 3022

Processing Papers 3023 - 3024

Processing Papers 3025 - 3026

Processing Papers 3027 - 3028

Processing Papers 3029 - 3030
Progress Saved

Processing Papers 3031 - 3032

Processing Papers 3033 - 3034

Processing Papers 3035 - 3036

Processing Papers 3037 - 3038

Processing Papers 3039 - 3040
Progress Saved

Processing Papers 3041 - 3042

Processing Papers 3043 - 3044

Processing Papers 3045 - 3046

Processing Papers 3047 - 3048

Processing Papers 3049 - 3050
Progress Saved

Processing Papers 3051 - 3052

Processing Papers 3053 - 3054

Processing Papers 3055 - 3056

Processing Papers 3057 - 3058

Processing Papers 3059 - 3060
Progress Saved

Processing Papers 3061 - 3062

Processing Papers 3063 - 3064

Processing Papers 3065 - 3066

Processing Papers 3067 - 3068

Processing Papers 3069 - 3070
Progress Saved

Processing Papers 3071 - 3072

Processing Papers 3073 - 3074

Processing Papers 3075 - 3076

Processing Papers 3077 - 3078

Processing Papers 3079 - 3080
Progress Saved

Processing Papers 3081 - 3082

Processing Papers 3083 - 3084

Processing Papers 3085 - 3086

Processing Papers 3087 - 3088

Processing Papers 3089 - 3090
Progress Saved

Processing Papers 3091 - 3092

Processing Papers 3093 - 3094

Processing Papers 3095 - 3096

Processing Papers 3097 - 3098

Processing Papers 3099 - 3100
Progress Saved

Processing Papers 3101 - 3102

Processing Papers 3103 - 3104

Processing Papers 3105 - 3106

Processing Papers 3107 - 3108

Processing Papers 3109 - 3110
Progress Saved

Processing Papers 3111 - 3112

Processing Papers 3113 - 3114

Processing Papers 3115 - 3116

Processing Papers 3117 - 3118

Processing Papers 3119 - 3120
Progress Saved

Processing Papers 3121 - 3122

Processing Papers 3123 - 3124

Processing Papers 3125 - 3126

Processing Papers 3127 - 3128

Processing Papers 3129 - 3130
Progress Saved

Processing Papers 3131 - 3132

Processing Papers 3133 - 3134

Processing Papers 3135 - 3136

Processing Papers 3137 - 3138

Processing Papers 3139 - 3140
Progress Saved

Processing Papers 3141 - 3142

Processing Papers 3143 - 3144

Processing Papers 3145 - 3146

Processing Papers 3147 - 3148

Processing Papers 3149 - 3150
Progress Saved

Processing Papers 3151 - 3152

Processing Papers 3153 - 3154

Processing Papers 3155 - 3156

Processing Papers 3157 - 3158

Processing Papers 3159 - 3160
Progress Saved

Processing Papers 3161 - 3162

Processing Papers 3163 - 3164

Processing Papers 3165 - 3166

Processing Papers 3167 - 3168

Processing Papers 3169 - 3170
Progress Saved

Processing Papers 3171 - 3172

Processing Papers 3173 - 3174

Processing Papers 3175 - 3176

Processing Papers 3177 - 3178

Processing Papers 3179 - 3180
Progress Saved

Processing Papers 3181 - 3182

Processing Papers 3183 - 3184

Processing Papers 3185 - 3186

Processing Papers 3187 - 3188

Processing Papers 3189 - 3190
Progress Saved

Processing Papers 3191 - 3192

Processing Papers 3193 - 3194

Processing Papers 3195 - 3196

Processing Papers 3197 - 3198

Processing Papers 3199 - 3200
Progress Saved

Processing Papers 3201 - 3202

Processing Papers 3203 - 3204

Processing Papers 3205 - 3206

Processing Papers 3207 - 3208

Processing Papers 3209 - 3210
Progress Saved

Processing Papers 3211 - 3212

Processing Papers 3213 - 3214

Processing Papers 3215 - 3216

Processing Papers 3217 - 3218

Processing Papers 3219 - 3220
Progress Saved

Processing Papers 3221 - 3222

Processing Papers 3223 - 3224

Processing Papers 3225 - 3226

Processing Papers 3227 - 3228

Processing Papers 3229 - 3230
Progress Saved

Processing Papers 3231 - 3232

Processing Papers 3233 - 3234

Processing Papers 3235 - 3236

Processing Papers 3237 - 3238

Processing Papers 3239 - 3240
Progress Saved

Processing Papers 3241 - 3242

Processing Papers 3243 - 3244

Processing Papers 3245 - 3246

Processing Papers 3247 - 3248

Processing Papers 3249 - 3250
Progress Saved

Processing Papers 3251 - 3252

Processing Papers 3253 - 3254

Processing Papers 3255 - 3256

Processing Papers 3257 - 3258

Processing Papers 3259 - 3260
Progress Saved

Processing Papers 3261 - 3262

Processing Papers 3263 - 3264

Processing Papers 3265 - 3266

Processing Papers 3267 - 3268

Processing Papers 3269 - 3270
Progress Saved

Processing Papers 3271 - 3272

Processing Papers 3273 - 3274

Processing Papers 3275 - 3276

Processing Papers 3277 - 3278

Processing Papers 3279 - 3280
Progress Saved

Processing Papers 3281 - 3282

Processing Papers 3283 - 3284

Processing Papers 3285 - 3286

Processing Papers 3287 - 3288

Processing Papers 3289 - 3290
Progress Saved

Processing Papers 3291 - 3292

Processing Papers 3293 - 3294

Processing Papers 3295 - 3296

Processing Papers 3297 - 3298

Processing Papers 3299 - 3300
Progress Saved

Processing Papers 3301 - 3302

Processing Papers 3303 - 3304

Processing Papers 3305 - 3306

Processing Papers 3307 - 3308

Processing Papers 3309 - 3310
Progress Saved

Processing Papers 3311 - 3312

Processing Papers 3313 - 3314

Processing Papers 3315 - 3316

Processing Papers 3317 - 3318

Processing Papers 3319 - 3320
Progress Saved

Processing Papers 3321 - 3322

Processing Papers 3323 - 3324

Processing Papers 3325 - 3326

Processing Papers 3327 - 3328

Processing Papers 3329 - 3330
Progress Saved

Processing Papers 3331 - 3332

Processing Papers 3333 - 3334

Processing Papers 3335 - 3336

Processing Papers 3337 - 3338

Processing Papers 3339 - 3340
Progress Saved

Processing Papers 3341 - 3342

Processing Papers 3343 - 3344

Processing Papers 3345 - 3346

Processing Papers 3347 - 3348

Processing Papers 3349 - 3350
Progress Saved

Processing Papers 3351 - 3352

Processing Papers 3353 - 3354

Processing Papers 3355 - 3356

Processing Papers 3357 - 3358

Processing Papers 3359 - 3360
Progress Saved

Processing Papers 3361 - 3362

Processing Papers 3363 - 3364

Processing Papers 3365 - 3366

Processing Papers 3367 - 3368

Processing Papers 3369 - 3370
Progress Saved

Processing Papers 3371 - 3372

Processing Papers 3373 - 3374

Processing Papers 3375 - 3376

Processing Papers 3377 - 3378

Processing Papers 3379 - 3380
Progress Saved

Processing Papers 3381 - 3382

Processing Papers 3383 - 3384

Processing Papers 3385 - 3386

Processing Papers 3387 - 3388

Processing Papers 3389 - 3390
Progress Saved

Processing Papers 3391 - 3392

Processing Papers 3393 - 3394

Processing Papers 3395 - 3396

Processing Papers 3397 - 3398

Processing Papers 3399 - 3400
Progress Saved

Processing Papers 3401 - 3402

Processing Papers 3403 - 3404

Processing Papers 3405 - 3406

Processing Papers 3407 - 3408

Processing Papers 3409 - 3410
Progress Saved

Processing Papers 3411 - 3412

Processing Papers 3413 - 3414

Processing Papers 3415 - 3416

Processing Papers 3417 - 3418

Processing Papers 3419 - 3420
Progress Saved

Processing Papers 3421 - 3422

Processing Papers 3423 - 3424

Processing Papers 3425 - 3426

Processing Papers 3427 - 3428
Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite\nPlease retry in 4.689260894s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.1-flash-lite'}, 'quotaValue': '500'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '4s'}]}}
Emergency Save Done

In [ ]:
with open(output_ANNOTATIONS_json, "r", encoding="utf-8") as f:

    annotations = json.load(f)


print("Output File :", output_ANNOTATIONS_json)

print("Processed Papers :", len(annotations))

if len(annotations) > 0:

    print("Last Dataset ID :", annotations[-1]["id"])

print("Remaining Papers :", len(list_of_dict_papers)-len(annotations))

Output File : auto_annotations_5000.json
Processed Papers : 3426
Last Dataset ID : 3425
Remaining Papers : 1574

#### 1.7.0. Rename the file "auto_annotations_Y(i.e no. of rows or paper actually annoted).json"

### → Change values here

In [ ]:
# ==========================
# CONFIGURATION
# ==========================
actual_papers = len(annotations)
NUM_PAPERS = actual_papers

print("Using dataset size:", NUM_PAPERS)

Using dataset size: 3426

In [ ]:
# ==========================
# CONFIGURATION
# ==========================
import os

old_file = "auto_annotations_5000.json"
new_file = f"auto_annotations_{actual_papers}.json"

if os.path.exists(old_file):
    os.rename(old_file, new_file)

In [ ]:
# ==========================
# CONFIGURATION
# ==========================
output_ANNOTATIONS_json = f"auto_annotations_{NUM_PAPERS}.json"
input_ANNOTATIONS_json = f"auto_annotations_{NUM_PAPERS}.json"

output_GOLD_json = f"gold_annotations_{NUM_PAPERS}.json"
input_GOLD_json = f"gold_annotations_{NUM_PAPERS}.json"

output_NORMALIZED_GOLD_json = f"normalized_gold_annotations_{NUM_PAPERS}.json"
input_NORMALIZED_GOLD_json = f"normalized_gold_annotations_{NUM_PAPERS}.json"

output_BIO_json = f"bio_dataset_{NUM_PAPERS}.json"
input_BIO_json = f"bio_dataset_{NUM_PAPERS}.json"

#### 1.7.1. Count the NER label (e.g., TASK, DATASET) & Entities

In [ ]:
# Counts the total occurrences of each NER label across all annotated papers.
# Shows the distribution of entity types in the dataset.

from collections import Counter
counter = Counter()

for item in annotations:

    ents = json.loads(
        item["annotation"]
    )

    for e in ents["entities"]:

        counter[e["label"]] += 1

print(counter)

Counter({'ALGORITHM': 8640, 'TASK': 3609, 'METRIC': 1129, 'DATASET': 1119})

In [ ]:
# Counts the frequency of each entity for every NER label (e.g., TASK, DATASET, MODEL).
# Helps analyze which entities are most common in the annotated dataset.

from collections import defaultdict, Counter

stats = defaultdict(Counter)

for item in annotations:
    ents = json.loads(item["annotation"])

    for e in ents["entities"]:
        stats[e["label"]][e["entity"].strip()] += 1


for label in stats:
    print("\n" + "="*60)
    print(label)
    print("="*60)

    for ent, cnt in stats[label].most_common(50):
        print(f"{cnt:3d}  {ent}")

============================================================
ALGORITHM
============================================================
104  deep neural networks
 80  CNN
 73  neural network
 71  neural networks
 57  deep neural network
 54  deep learning
 51  reinforcement learning
 45  convolutional neural network
 45  convolutional neural networks
 42  LSTM
 37  stochastic gradient descent
 36  GAN
 35  CNNs
 34  deep reinforcement learning
 33  DNN
 32  Deep neural networks
 31  SVM
 31  GANs
 29  Transformer
 26  logistic regression
 26  GNNs
 25  gradient descent
 25  SGD
 24  RNN
 24  Deep Neural Networks
 24  autoencoder
 23  recurrent neural networks
 22  BERT
 21  Deep Learning
 21  Gaussian processes
 21  RNNs
 19  Generative Adversarial Networks
 19  Gaussian process
 18  graph neural network
 18  Convolutional Neural Networks
 18  Bayesian optimization
 18  generative adversarial networks
 18  Graph Neural Networks
 17  GNN
 17  VAE
 16  DNNs
 16  ResNet
 16  transfer learning
 15  Support Vector Machine
 15  Convolutional Neural Network
 15  Random Forest
 15  graph neural networks
 14  random forest
 14  Reinforcement Learning
 14  PCA

============================================================
DATASET
============================================================
 70  MNIST
 64  ImageNet
 60  CIFAR-10
 23  CIFAR-100
 20  CIFAR10
 16  SVHN
 12  CelebA
  8  CIFAR100
  8  LibriSpeech
  8  MuJoCo
  8  Atari
  6  GLUE
  6  STL-10
  5  CIFAR
  5  Twitter
  4  KITTI
  4  LSUN
  4  Hopper
  4  Atari 2600
  4  Cityscapes
  4  COCO
  4  Fashion MNIST
  4  CARLA
  3  UCI datasets
  3  The Cancer Genome Atlas
  3  PubMed
  3  HalfCheetah
  3  Fashion-MNIST
  3  Atari games
  3  Web of Science
  3  Kinetics-600
  3  MSCOCO
  3  Visual Genome
  3  FashionMNIST
  3  Cartpole
  3  Wikipedia
  3  Omniglot
  2  COCO 2017
  2  GTSRB
  2  VoxCeleb
  2  Lunar Lander
  2  ImageNet-R
  2  CHiME-4
  2  AWA2
  2  GridWorld
  2  IEEE
  2  Kinetics-400
  2  Kinetics-700
  2  Ant
  2  Scopus

============================================================
TASK
============================================================
142  classification
 58  image classification
 47  regression
 43  clustering
 34  prediction
 31  speech recognition
 27  link prediction
 25  feature selection
 25  object detection
 24  Clustering
 20  anomaly detection
 20  reinforcement learning
 19  binary classification
 17  node classification
 15  semi-supervised learning
 15  semantic segmentation
 14  supervised learning
 14  segmentation
 14  machine translation
 13  recommendation
 13  image recognition
 12  few-shot learning
 12  multi-label classification
 12  text classification
 11  language modeling
 11  structured prediction
 11  Image Classification
 11  linear regression
 11  matrix completion
 11  image segmentation
 11  face recognition
 10  dimensionality reduction
 10  transfer learning
 10  forecasting
 10  multi-task learning
 10  domain adaptation
  9  metric learning
  9  active learning
  9  sentiment classification
  9  multi-class classification
  9  outlier detection
  9  sentiment analysis
  9  object recognition
  9  optimization
  9  imitation learning
  9  density estimation
  9  Reinforcement Learning
  8  Classification
  8  image generation
  8  Recommendation

============================================================
METRIC
============================================================
269  accuracy
 97  Accuracy
 26  classification accuracy
 22  AUC
 20  precision
 19  recall
 14  F1 score
 12  BLEU
 11  predictive accuracy
 11  prediction accuracy
 10  F1
  9  top-1 accuracy
  9  F1-score
  7  WER
  7  test accuracy
  6  F1 scores
  6  word error rate
  6  MSE
  5  SSIM
  5  regret
  5  false positive rate
  5  accuracies
  5  mean squared error
  5  RMSE
  4  AUROC
  4  robust accuracy
  4  MOS
  4  R-squared
  4  classification accuracies
  4  FID
  4  sensitivity
  4  mAP
  4  specificity
  3  attack success rate
  3  NDCG
  3  Precision
  3  Recall
  3  CER
  3  AP
  3  perplexity
  3  MAE
  3  Dice score
  3  mean absolute error
  3  Word Error Rate
  3  sample complexity
  3  PSNR
  3  model accuracy
  3  prediction error
  3  mean opinion score
  2  diarization error rate

## 🌟 STEP 2 - Clean the "auto_annotations_x(i.e no. of rows).json" and save the "gold_annotations_x(i.e no. of rows).json"

### → Change values here

In [ ]:
# ==========================
# CONFIGURATION
# ==========================

# INPUT FILES
input_ANNOTATIONS_json = f"auto_annotation_{NUM_PAPERS}.json"

# OUTPUT FILES
OUTPUT_gold_JSON = f"gold_annotations_{NUM_PAPERS}.json"

### 2.1. Import Libraries &  Load the "auto_annotations_x(i.e no. of rows).json" file

In [ ]:
import json
from tqdm import tqdm

In [ ]:
with open(input_ANNOTATIONS_json, "r", encoding="utf-8") as f:
    annotations = json.load(f)

print("Loaded:", len(annotations), "papers")

Loaded: 3426 papers

### 2.2. Bad entity

In [ ]:
bad_entities = {

    # Generic concepts
    "training",
    "prediction",
    "generalisation",
    "learning",
    "occupation",
    "reinforcement",
    "sampling efficiency",
    "surrogate",
    "emulation",
    "optimization",
    "qubo",

    # Generic paradigms
    "machine learning",
    "deep learning",
    "artificial intelligence",

    # Generic neural-network umbrella terms
    "neural network",
    "neural networks",
    "deep neural network",
    "deep neural networks",

    # Generic tasks
    "predicting",
    "classify",
    "classification",
    "clustering",
    "regression",
    "linear regression",
    "detection",
    "segmentation",
    "planning",
    "ranking",
    "reconstruction",
    "inference",
    "prediction",

    # Generic learning types
    "online learning",
    "representation learning",
    "supervised learning",
    "unsupervised learning",
    "active learning"
}

In [ ]:
manual_bad_entities = {

    # Wrong dataset predictions
    "cern large hadron collider",
    "tic-tac-toe",

    # Generic dataset words
    "dataset",
    "datasets",
    "benchmark",
    "benchmarks",

    # Generic entity words
    "method",
    "methods",
    "approach",
    "approaches",
    "framework",
    "frameworks",
    "model",
    "models",

    # Noisy datasets from inspection
    "ieee",
    "rooms task",
    "high variance rooms task"
}

### 2.3. Canonical Mapping

In [ ]:
canonical = {

    # CNN
    "cnn": "Convolutional Neural Network",
    "cnns": "Convolutional Neural Network",
    "convolutional neural network": "Convolutional Neural Network",
    "convolutional neural networks": "Convolutional Neural Network",

    # RNN
    "rnn": "Recurrent Neural Network",
    "rnns": "Recurrent Neural Network",
    "recurrent neural network": "Recurrent Neural Network",
    "recurrent neural networks": "Recurrent Neural Network",

    # DNN
    "dnn": "Deep Neural Network",
    "dnns": "Deep Neural Network",

    # GNN
    "gnn": "Graph Neural Network",
    "gnns": "Graph Neural Network",
    "graph neural network": "Graph Neural Network",
    "graph neural networks": "Graph Neural Network",

    # GAN
    "gan": "Generative Adversarial Network",
    "gans": "Generative Adversarial Network",
    "generative adversarial network": "Generative Adversarial Network",
    "generative adversarial networks": "Generative Adversarial Network",

    # Transformer
    "transformer": "Transformer",
    "transformers": "Transformer",

    # SGD
    "sgd": "Stochastic Gradient Descent",
    "stochastic gradient descent": "Stochastic Gradient Descent",

    # LSTM
    "lstm": "Long Short-Term Memory",
    "long short-term memory": "Long Short-Term Memory",

    # GRU
    "gru": "Gated Recurrent Unit",
    "gated recurrent unit": "Gated Recurrent Unit",

    # MLP
    "mlp": "Multi-Layer Perceptron",
    "multi-layer perceptron": "Multi-Layer Perceptron",

    # GCN
    "graph convolutional network": "Graph Convolutional Network",
    "graph convolutional networks": "Graph Convolutional Network",

    # BERT
    "bert-base": "BERT",
    "bert-large": "BERT",

    # Datasets
    "imagenet": "ImageNet",
    "imagenet-subset": "ImageNet-Subset",

    "mnist": "MNIST",

    "cifar10": "CIFAR-10",
    "cifar-10": "CIFAR-10",

    "cifar100": "CIFAR-100",
    "cifar-100": "CIFAR-100",

    "fashionmnist": "Fashion-MNIST",
    "fashion-mnist": "Fashion-MNIST",

    "svhn": "SVHN",

    "coco": "COCO",
    "mscoco": "COCO",

    # Architecture normalization
    "dense net 121": "DenseNet121",
    "densenet 121": "DenseNet121",

    "resnet 34": "ResNet34",
    "resnet 50": "ResNet50",

    "vgg 19": "VGG19",

    # Metrics
    "accuracy": "Accuracy",
    "accuracies": "Accuracy",
    "classification accuracy": "Accuracy",

    "precision": "Precision",
    "recall": "Recall",

    "f1": "F1",
    "f1 score": "F1",
    "f1 scores": "F1",
    "f1-score": "F1",

    "mean squared error": "MSE",
    "mean absolute error": "MAE",

    "word error rate": "WER",
    "word error rates": "WER",

    "auroc": "ROC-AUC",
    "roc-auc": "ROC-AUC"
}

In [ ]:
canonical.update({

    # Metrics
    "f1-scores": "F1",
    "f-measure": "F1",
    "sensitivity": "Sensitivity",

    "classification accuracies": "Accuracy",
    "prediction accuracy": "Accuracy",
    "predictive accuracy": "Accuracy",
    "test accuracy": "Accuracy",
    "standard accuracy": "Accuracy",
    "accuracy": "Accuracy",

    "precision": "Precision",
    "recall": "Recall",

    "f1 score": "F1",
    "f1 scores": "F1",
    "f1-score": "F1",
    "macro-f1": "F1",
    "f-1 score": "F1",

    "auc": "AUC",
    "roc-auc": "ROC-AUC",

    "word error rate": "WER",

    "mean squared error": "MSE",
    "mean absolute error": "MAE",
    "root mean squared error": "RMSE",


    # Models / Algorithms
    "svm": "Support Vector Machine",
    "support vector machine": "Support Vector Machine",
    "support vector machines": "Support Vector Machine",

    "lstm": "Long Short-Term Memory",
    "lstms": "Long Short-Term Memory",
    "long short-term memory": "Long Short-Term Memory",

    "gru": "Gated Recurrent Unit",
    "gated recurrent unit": "Gated Recurrent Unit",

    "vae": "Variational Autoencoder",
    "vaes": "Variational Autoencoder",
    "variational autoencoder": "Variational Autoencoder",
    "variational autoencoders": "Variational Autoencoder",

    "mlp": "Multi-Layer Perceptron",
    "multi-layer perceptron": "Multi-Layer Perceptron",

    "mcmc": "Markov Chain Monte Carlo",
    "markov chain monte carlo": "Markov Chain Monte Carlo",

    "reinforcement learning": "Reinforcement Learning",
    "deep reinforcement learning": "Deep Reinforcement Learning",

    "gradient descent": "Gradient Descent",

    "gaussian process": "Gaussian Process",
    "gaussian processes": "Gaussian Process",

    "autoencoder": "Autoencoder",
    "autoencoders": "Autoencoder",

    "k-means": "K-Means",
    "kmeans": "K-Means",

    "artificial neural network": "Artificial Neural Network",
    "artificial neural networks": "Artificial Neural Network"
})

In [ ]:
bad_entities.update({
    "reinforcement learning"
})

manual_bad_entities.update({
    "multi-task learning"
})

### 2.4. Create the gold data

In [ ]:
gold = []

for item in tqdm(annotations):

    entities = json.loads(
        item["annotation"]
    )["entities"]

    cleaned = []
    seen = set()

    for ent in entities:

        entity = ent["entity"].strip()
        label = ent["label"]

        # --------------------
        # TASK normalization
        # --------------------
        if label == "TASK":
            entity = entity.lower()

        entity_lower = entity.lower()

        # --------------------
        # Remove tiny entities
        # --------------------
        if len(entity) < 3:
            continue

        # --------------------
        # Remove generic junk
        # --------------------
        if entity_lower in {
            "method",
            "approach",
            "framework",
            "model"
        }:
            continue

        # --------------------
        # Remove bad entities
        # --------------------
        if (
            entity_lower in bad_entities
            or entity_lower in manual_bad_entities
        ):
            continue

        # --------------------
        # Canonical mapping
        # --------------------
        if entity_lower in canonical:
            entity = canonical[entity_lower]

        # --------------------
        # Duplicate removal
        # --------------------
        key = (
            entity.lower(),
            label
        )

        if key in seen:
            continue

        seen.add(key)

        cleaned.append({
            "entity": entity,
            "label": label
        })

    gold.append({
        "id": item["id"],
        "abstract": item["abstract"],
        "entities": cleaned
    })

print("\nGold annotations created :", len(gold))

100%|██████████| 3426/3426 [00:00<00:00, 79378.69it/s]

Gold annotations created : 3426

In [ ]:
from collections import Counter

algo_counter = Counter()
dataset_counter = Counter()
task_counter = Counter()
metric_counter = Counter()

for paper in gold:

    for ent in paper["entities"]:

        if ent["label"] == "ALGORITHM":
            algo_counter[ent["entity"]] += 1

        elif ent["label"] == "DATASET":
            dataset_counter[ent["entity"]] += 1

        elif ent["label"] == "TASK":
            task_counter[ent["entity"]] += 1

        elif ent["label"] == "METRIC":
            metric_counter[ent["entity"]] += 1


print("="*60)
print("ALGORITHM")
print("="*60)

for k, v in algo_counter.most_common(50):
    print(f"{v:3d}  {k}")

print("\n" + "="*60)
print("DATASET")
print("="*60)

for k, v in dataset_counter.most_common(50):
    print(f"{v:3d}  {k}")

print("\n" + "="*60)
print("TASK")
print("="*60)

for k, v in task_counter.most_common(50):
    print(f"{v:3d}  {k}")

print("\n" + "="*60)
print("METRIC")
print("="*60)

for k, v in metric_counter.most_common(50):
    print(f"{v:3d}  {k}")

============================================================
ALGORITHM
============================================================
181  Convolutional Neural Network
 76  Generative Adversarial Network
 72  Recurrent Neural Network
 65  Graph Neural Network
 58  Support Vector Machine
 57  Long Short-Term Memory
 53  Transformer
 51  Deep Reinforcement Learning
 51  Stochastic Gradient Descent
 50  Gaussian Process
 49  Deep Neural Network
 47  Variational Autoencoder
 36  Autoencoder
 27  Gradient Descent
 26  logistic regression
 24  Artificial Neural Network
 22  BERT
 22  Markov Chain Monte Carlo
 18  K-Means
 18  Bayesian optimization
 16  ResNet
 16  transfer learning
 15  Random Forest
 14  random forest
 14  PCA
 14  Graph Convolutional Network
 13  ReLU
 12  Q-learning
 11  adversarial training
 10  ADMM
 10  Multi-Layer Perceptron
 10  SVD
  9  knowledge distillation
  9  Gated Recurrent Unit
  9  U-Net
  9  deep convolutional neural network
  9  dynamic programming
  9  ResNet-50
  9  Adam
  9  decision trees
  9  XGBoost
  9  Federated learning
  9  federated learning
  9  NMF
  9  GCNs
  9  variational inference
  8  bagging
  8  random forests
  8  PyTorch
  8  Bayesian neural networks

============================================================
DATASET
============================================================
 81  CIFAR-10
 70  MNIST
 66  ImageNet
 32  CIFAR-100
 16  SVHN
 12  CelebA
  8  LibriSpeech
  8  MuJoCo
  8  Atari
  7  COCO
  6  GLUE
  6  STL-10
  6  Fashion-MNIST
  5  CIFAR
  5  Twitter
  4  KITTI
  4  LSUN
  4  Hopper
  4  Atari 2600
  4  Cityscapes
  4  Fashion MNIST
  4  CARLA
  3  UCI datasets
  3  The Cancer Genome Atlas
  3  PubMed
  3  HalfCheetah
  3  Atari games
  3  Web of Science
  3  Kinetics-600
  3  Visual Genome
  3  Cartpole
  3  Wikipedia
  3  Omniglot
  2  COCO 2017
  2  GTSRB
  2  VoxCeleb
  2  Lunar Lander
  2  ImageNet-R
  2  CHiME-4
  2  AWA2
  2  GridWorld
  2  Kinetics-400
  2  Kinetics-700
  2  Ant
  2  Scopus
  2  Atari 100k
  2  VeRi
  2  FEMNIST
  2  UCI data sets
  2  HotpotQA

============================================================
TASK
============================================================
 69  image classification
 33  feature selection
 32  speech recognition
 31  object detection
 29  link prediction
 25  anomaly detection
 21  recommendation
 19  binary classification
 18  semi-supervised learning
 18  machine translation
 17  node classification
 17  semantic segmentation
 14  few-shot learning
 14  text classification
 14  face recognition
 13  image recognition
 12  transfer learning
 12  multi-label classification
 12  structured prediction
 12  sentiment analysis
 12  automatic speech recognition
 11  imitation learning
 11  language modeling
 11  domain adaptation
 11  matrix completion
 11  image segmentation
 11  question answering
 10  dimensionality reduction
 10  metric learning
 10  forecasting
 10  time series forecasting
  9  neural architecture search
  9  continual learning
  9  sentiment classification
  9  multi-class classification
  9  outlier detection
  9  object recognition
  9  graph classification
  9  density estimation
  8  neural machine translation
  8  image generation
  7  visual question answering
  7  image denoising
  7  uncertainty estimation
  7  text generation
  7  continuous control
  7  unsupervised domain adaptation
  7  variable selection
  7  community detection
  7  emotion recognition

============================================================
METRIC
============================================================
429  Accuracy
 37  F1
 23  Precision
 22  AUC
 22  Recall
 17  WER
 12  BLEU
 11  MSE
  9  top-1 accuracy
  7  ROC-AUC
  6  RMSE
  6  MAE
  6  Sensitivity
  5  SSIM
  5  regret
  5  false positive rate
  4  robust accuracy
  4  MOS
  4  R-squared
  4  FID
  4  mAP
  4  specificity
  3  attack success rate
  3  NDCG
  3  CER
  3  perplexity
  3  Dice score
  3  sample complexity
  3  PSNR
  3  model accuracy
  3  prediction error
  3  mean opinion score
  2  diarization error rate
  2  PER
  2  Hamming loss
  2  Average Precision
  2  detection rate
  2  log-likelihood
  2  expected calibration error
  2  MMD
  2  reconstruction accuracy
  2  Earth Mover's Distance
  2  error rate
  2  area under the curve
  2  Bayesian information criterion
  2  Top-1
  2  mean-squared-error
  2  MRR
  2  Dice
  2  mean square error

### 2.5. Save

In [ ]:
with open(
    output_GOLD_json,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        gold,
        f,
        indent=2,
        ensure_ascii=False
    )

print("Saved:", output_GOLD_json)

Saved: gold_annotations_3426.json

#### 2.5.1. Preview

In [ ]:
for i in range(5):
    print("\nID:", gold[i]["id"])
    print(gold[i]["entities"])

ID: 0
[{'entity': 'epsilon-Consistent Mixup', 'label': 'ALGORITHM'}, {'entity': 'Mixup', 'label': 'ALGORITHM'}, {'entity': 'SVHN', 'label': 'DATASET'}, {'entity': 'CIFAR-10', 'label': 'DATASET'}, {'entity': 'semi-supervised classification', 'label': 'TASK'}, {'entity': 'Accuracy', 'label': 'METRIC'}]

ID: 1
[{'entity': 'Autoencoder', 'label': 'ALGORITHM'}, {'entity': 'graph-based autoencoders', 'label': 'ALGORITHM'}, {'entity': 'Graph Neural Network', 'label': 'ALGORITHM'}, {'entity': 'anomaly detection', 'label': 'TASK'}]

ID: 2
[{'entity': 'Gaussian models', 'label': 'ALGORITHM'}, {'entity': 'feature selection', 'label': 'TASK'}]

ID: 3
[{'entity': 'Convolutional Neural Network', 'label': 'ALGORITHM'}, {'entity': 'ResNet34', 'label': 'ALGORITHM'}, {'entity': 'ResNet50', 'label': 'ALGORITHM'}, {'entity': 'VGG19', 'label': 'ALGORITHM'}, {'entity': 'DenseNet121', 'label': 'ALGORITHM'}, {'entity': 'skin lesion detection', 'label': 'TASK'}, {'entity': 'Accuracy', 'label': 'METRIC'}]

ID: 4
[]

### 2.6. Normalize the "gold_annotations_x(i.e no. of rows).json" file

In [ ]:
import json
import re

def normalize_text(text):
    # $...$ -> ...
    text = re.sub(r'\$([^$]+)\$', r'\1', text)

    # \epsilon -> epsilon
    text = re.sub(r'\\([A-Za-z]+)', r'\1', text)

    # Normalize whitespace
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

# Load gold dataset
with open(input_GOLD_json, "r", encoding="utf-8") as f:
    data = json.load(f)

# Normalize abstracts
for item in data:
    if "abstract" in item:
        item["abstract"] = normalize_text(item["abstract"])

# Save new file
with open(
    output_NORMALIZED_GOLD_json,
    "w",
    encoding="utf-8"
) as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Saved:", output_NORMALIZED_GOLD_json)

Saved: normalized_gold_annotations_3426.json

## 🌟 STEP 3 - Perform the BIO tagging and save the "bio_dataset_x(i.e no. of rows).json"

### → Change values here

In [ ]:
# ==========================
# CONFIGURATION
# ==========================

# INPUT FILES
input_NORMALIZED_GOLD_json = f"normalized_gold_annotations_{NUM_PAPERS}.json"

# OUTPUT FILES
output_BIO_json = f"bio_dataset_{NUM_PAPERS}.json"

### 3.1. Import Libraries &  Load the "normalized_gold_annotations_x(i.e no. of rows).json" file

In [ ]:
import json
import re

Loaded: 1430

In [ ]:
with open(
    input_NORMALIZED_GOLD_json,
    "r",
    encoding="utf-8"
) as f:

    gold = json.load(f)

print("Loaded:", len(gold))

Loaded: 3426

### 3.2. Create the Gold dictionary

In [ ]:
gold_dict = {}

for item in gold:

    gold_dict[
        item["id"]
    ] = item["entities"]

print(
    "Gold dict size:",
    len(gold_dict)
)

Gold dict size: 3426

### 3.3. Generate BIO Dataset

In [ ]:
dataset = []

for paper in gold:

    pid = paper["id"]

    text = paper["abstract"]

    tokens = re.findall(
        r"\w+|[^\w\s]",
        text
    )

    labels = ["O"] * len(tokens)

    entities = gold_dict.get(
        pid,
        []
    )

    entities = sorted(
            entities,
            key=lambda x: len(x["entity"]),
            reverse=True
    )

    lower_tokens = [
        t.lower()
        for t in tokens
    ]

    for ent in entities:

        ent_tokens = re.findall(
            r"\w+|[^\w\s]",
            ent["entity"]
        )

        ent_tokens = [
            x.lower()
            for x in ent_tokens
        ]

        n = len(ent_tokens)

        for i in range(
            len(tokens) - n + 1
        ):

            if (
                lower_tokens[i:i+n]
                ==
                ent_tokens
            ):

                if labels[i] != "O":
                    continue

                labels[i] = (
                    "B-" +
                    ent["label"]
                )

                for j in range(
                    1,
                    n
                ):

                    if (
                        labels[i+j]
                        ==
                        "O"
                    ):

                        labels[i+j] = (
                            "I-" +
                            ent["label"]
                        )

    dataset.append({

        "id": pid,

        "tokens": tokens,

        "ner_tags": labels

    })

print(
    "BIO dataset created:",
    len(dataset)
)

BIO dataset created: 3426

### 3.4. Verify BIO Tags

In [ ]:
for token, tag in zip(

    dataset[0]["tokens"],

    dataset[0]["ner_tags"]

):

    if tag != "O":

        print(
            f"{token:20} {tag}"
        )

epsilon              B-ALGORITHM
-                    I-ALGORITHM
Consistent           I-ALGORITHM
Mixup                I-ALGORITHM
Mixup                B-ALGORITHM
Mixup                B-ALGORITHM
semi                 B-TASK
-                    I-TASK
supervised           I-TASK
classification       I-TASK
accuracy             B-METRIC
SVHN                 B-DATASET
Mixup                B-ALGORITHM
Mixup                B-ALGORITHM

In [ ]:
for token, tag in zip(
    dataset[0]["tokens"],
    dataset[0]["ner_tags"]
):
    if tag != "O":
        print(token, tag)

epsilon B-ALGORITHM
- I-ALGORITHM
Consistent I-ALGORITHM
Mixup I-ALGORITHM
Mixup B-ALGORITHM
Mixup B-ALGORITHM
semi B-TASK
- I-TASK
supervised I-TASK
classification I-TASK
accuracy B-METRIC
SVHN B-DATASET
Mixup B-ALGORITHM
Mixup B-ALGORITHM

In [ ]:
print(gold[0]["entities"])

[{'entity': 'epsilon-Consistent Mixup', 'label': 'ALGORITHM'}, {'entity': 'Mixup', 'label': 'ALGORITHM'}, {'entity': 'SVHN', 'label': 'DATASET'}, {'entity': 'CIFAR-10', 'label': 'DATASET'}, {'entity': 'semi-supervised classification', 'label': 'TASK'}, {'entity': 'Accuracy', 'label': 'METRIC'}]

In [ ]:
print(dataset[0]["tokens"][:50])

['In', 'this', 'paper', 'we', 'propose', 'epsilon', '-', 'Consistent', 'Mixup', '(', 'epsilonmu', ')', '.', 'epsilonmu', 'is', 'a', 'data', '-', 'based', 'structural', 'regularization', 'technique', 'that', 'combines', 'Mixup', "'", 's', 'linear', 'interpolation', 'with', 'consistency', 'regularization', 'in', 'the', 'Mixup', 'direction', ',', 'by', 'compelling', 'a', 'simple', 'adaptive', 'tradeoff', 'between', 'the', 'two', '.', 'This', 'learnable', 'combination']

### 3.5. Save the BIO Dataset Json File

In [ ]:
with open(
    output_BIO_json,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        dataset,
        f,
        indent=2,
        ensure_ascii=False
    )

print(
    "Saved:",
    output_BIO_json
)

Saved: bio_dataset_3426.json

In [ ]:
matched = 0
total = 0

for paper in gold:

    text = paper["abstract"].lower()

    for ent in paper["entities"]:

        total += 1

        entity = ent["entity"].lower()

        if entity in text:
            matched += 1

print("Total entities :", total)
print("Direct matches :", matched)
print("Coverage % :", round(100 * matched / total, 2))

Total entities : 13032
Direct matches : 12646
Coverage % : 97.04

In [ ]:
assert len(tokens) == len(ner_tags)

NameError: name 'ner_tags' is not defined

## 🌟 STEP 4 - Prep data for Training

In [ ]:
# Part A:
# Loaded the BIO-tagged NER dataset and verified token-label consistency.
# Split the dataset into train (80%), validation (10%), and test (10%) sets.
# Created label mappings (label2id and id2label) and converted BIO tags to numerical IDs.
# Converted the data into Hugging Face Dataset format for model training.

# Part B:
# Loaded the SciBERT tokenizer for scientific text processing.
# Tokenized the input tokens and aligned BIO labels with subword tokens.
# Verified sequence lengths, label IDs, and tokenization outputs.
# Saved the tokenized datasets, making them ready for SciBERT fine-tuning.

### → Change values here

In [ ]:
# ==========================
# CONFIGURATION
# ==========================

# input_BIO_json = f"bio_dataset_{NUM_PAPERS}.json"
input_BIO_json = "bio_dataset_3426.json"

label_map_json =  "label_mapping_3426.json"
# f"label_mapping_{NUM_PAPERS}.json"

MODEL_NAME = "allenai/scibert_scivocab_uncased"

### 4.1. Import Libraries &  Load the "bio_dataset_x(i.e no. of rows).json" file

In [ ]:
# !pip install transformers datasets accelerate -q

In [ ]:
import json
import random

from sklearn.model_selection import train_test_split
from datasets import Dataset

In [ ]:
with open(input_BIO_json, "r", encoding="utf-8") as f:
    data = json.load(f)

print(f"Total Papers Loaded: {len(data)}")

Total Papers Loaded: 3426

#### 4.1.1. Check or Confirm if the content/structure of the "bio_dataset_x(i.e no. of rows).json" file is correct

In [ ]:
print(data[0].keys())
print("\n",data[0])

dict_keys(['id', 'tokens', 'ner_tags'])

 {'id': 0, 'tokens': ['In', 'this', 'paper', 'we', 'propose', 'epsilon', '-', 'Consistent', 'Mixup', '(', 'epsilonmu', ')', '.', 'epsilonmu', 'is', 'a', 'data', '-', 'based', 'structural', 'regularization', 'technique', 'that', 'combines', 'Mixup', "'", 's', 'linear', 'interpolation', 'with', 'consistency', 'regularization', 'in', 'the', 'Mixup', 'direction', ',', 'by', 'compelling', 'a', 'simple', 'adaptive', 'tradeoff', 'between', 'the', 'two', '.', 'This', 'learnable', 'combination', 'of', 'consistency', 'and', 'interpolation', 'induces', 'a', 'more', 'flexible', 'structure', 'on', 'the', 'evolution', 'of', 'the', 'response', 'across', 'the', 'feature', 'space', 'and', 'is', 'shown', 'to', 'improve', 'semi', '-', 'supervised', 'classification', 'accuracy', 'on', 'the', 'SVHN', 'and', 'CIFAR10', 'benchmark', 'datasets', ',', 'yielding', 'the', 'largest', 'gains', 'in', 'the', 'most', 'challenging', 'low', 'label', '-', 'availability', 'scenarios', '.', 'Empirical', 'studies', 'comparing', 'epsilonmu', 'and', 'Mixup', 'are', 'presented', 'and', 'provide', 'insight', 'into', 'the', 'mechanisms', 'behind', 'epsilonmu', "'", 's', 'effectiveness', '.', 'In', 'particular', ',', 'epsilonmu', 'is', 'found', 'to', 'produce', 'more', 'accurate', 'synthetic', 'labels', 'and', 'more', 'confident', 'predictions', 'than', 'Mixup', '.'], 'ner_tags': ['O', 'O', 'O', 'O', 'O', 'B-ALGORITHM', 'I-ALGORITHM', 'I-ALGORITHM', 'I-ALGORITHM', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ALGORITHM', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ALGORITHM', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-TASK', 'I-TASK', 'I-TASK', 'I-TASK', 'B-METRIC', 'O', 'O', 'B-DATASET', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ALGORITHM', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ALGORITHM', 'O']}

In [ ]:
for sample in data:

    assert len(sample["tokens"]) == len(sample["ner_tags"]), (
        f"Mismatch Found in ID: {sample['id']}"
    )

print("All token or tag lengths match.")

All token or tag lengths match.

### 4.2. Create the Train / Validation / Test Split

In [ ]:
train_data, temp_data = train_test_split(
    data,
    test_size=0.20,
    random_state=SEED,
    shuffle=True
)

val_data, test_data = train_test_split(
    temp_data,
    test_size=0.50,
    random_state=SEED,
    shuffle=True
)

print("Dataset Split")
print("Train:", len(train_data))
print("Validation:", len(val_data))
print("Test:", len(test_data))

Dataset Split
Train: 2740
Validation: 343
Test: 343

### 4.3. Build Label Set and Create label2id & id2label and Save

In [ ]:
all_labels = set()

for sample in data:
    all_labels.update(sample["ner_tags"])

all_labels = sorted(list(all_labels))

print("Labels Found:")
print(all_labels)

print("\nTotal Labels:", len(all_labels))

Labels Found:
['B-ALGORITHM', 'B-DATASET', 'B-METRIC', 'B-TASK', 'I-ALGORITHM', 'I-DATASET', 'I-METRIC', 'I-TASK', 'O']

Total Labels: 9

In [ ]:
label2id = {
    label: idx
    for idx, label in enumerate(all_labels)
}

id2label = {
    idx: label
    for label, idx in label2id.items()
}

print("label2id:")
print(label2id)

print("\nid2label:")
print(id2label)

label2id:
{'B-ALGORITHM': 0, 'B-DATASET': 1, 'B-METRIC': 2, 'B-TASK': 3, 'I-ALGORITHM': 4, 'I-DATASET': 5, 'I-METRIC': 6, 'I-TASK': 7, 'O': 8}

id2label:
{0: 'B-ALGORITHM', 1: 'B-DATASET', 2: 'B-METRIC', 3: 'B-TASK', 4: 'I-ALGORITHM', 5: 'I-DATASET', 6: 'I-METRIC', 7: 'I-TASK', 8: 'O'}

#### 4.3.1. Save Label Mapping

In [ ]:
with open(label_map_json, "w", encoding="utf-8") as f:
    json.dump(
        {
            "label2id": label2id,
            "id2label": id2label
        },
        f,
        indent=4
    )

print("Label mapping saved.")

Label mapping saved.

### 4.4. Convert Labels to IDs

In [ ]:
for sample in train_data:

    sample["labels"] = [
        label2id[tag]
        for tag in sample["ner_tags"]
    ]

for sample in val_data:

    sample["labels"] = [
        label2id[tag]
        for tag in sample["ner_tags"]
    ]

for sample in test_data:

    sample["labels"] = [
        label2id[tag]
        for tag in sample["ner_tags"]
    ]

print("Labels converted to IDs.")

Labels converted to IDs.

### 4.5. Convert to Hugging Face Dataset

In [ ]:
train_ds = Dataset.from_list(train_data)

val_ds = Dataset.from_list(val_data)

test_ds = Dataset.from_list(test_data)

print("Hugging Face Dataset created.")

Hugging Face Dataset created.

#### 4.5.1. Verify

In [ ]:
print("Train Dataset")
print(train_ds)

print("\nValidation Dataset")
print(val_ds)

print("\nTest Dataset")
print(test_ds)

Train Dataset
Dataset({
    features: ['id', 'tokens', 'ner_tags', 'labels'],
    num_rows: 2740
})

Validation Dataset
Dataset({
    features: ['id', 'tokens', 'ner_tags', 'labels'],
    num_rows: 343
})

Test Dataset
Dataset({
    features: ['id', 'tokens', 'ner_tags', 'labels'],
    num_rows: 343
})

In [ ]:
print(train_ds[2]["tokens"][:50])
print(train_ds[2]["ner_tags"][:50])
print(train_ds[2]["labels"][:50])

['Reinforcement', 'Learning', '(', 'RL', ')', 'has', 'opened', 'up', 'new', 'opportunities', 'to', 'solve', 'a', 'wide', 'range', 'of', 'complex', 'decision', '-', 'making', 'tasks', '.', 'However', ',', 'modern', 'RL', 'algorithms', ',', 'e', '.', 'g', '.', ',', 'Deep', 'Q', '-', 'Learning', ',', 'are', 'based', 'on', 'deep', 'neural', 'networks', ',', 'putting', 'high', 'computational', 'costs', 'when']
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ALGORITHM', 'I-ALGORITHM', 'I-ALGORITHM', 'I-ALGORITHM', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 4, 4, 4, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]

In [ ]:
print(train_ds.features)

{'id': Value('int64'), 'tokens': List(Value('string')), 'ner_tags': List(Value('string')), 'labels': List(Value('int64'))}

In [ ]:
from collections import Counter

counter = Counter()

for sample in data:
    counter.update(sample["ner_tags"])

for label, count in sorted(counter.items()):
    print(f"{label:15} {count}")

B-ALGORITHM     10384
B-DATASET       1218
B-METRIC        1430
B-TASK          4074
I-ALGORITHM     14052
I-DATASET       1290
I-METRIC        894
I-TASK          6430
O               648450

### 4.6. Load SciBERT Tokenizer

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

print("\nTokenizer Loaded")

config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.txt:   0%|          | 0.00/228k [00:00<?, ?B/s]

Tokenizer Loaded

In [ ]:
sample = train_ds[0]["tokens"]

print(sample[:20])

encoded = tokenizer(
    sample,
    is_split_into_words=True
)

print(encoded.tokens()[:30])

['Tensor', 'decomposition', 'is', 'a', 'powerful', 'computational', 'tool', 'for', 'multiway', 'data', 'analysis', '.', 'Many', 'popular', 'tensor', 'decomposition', 'approaches', '-', '-', '-']
['[CLS]', 'tensor', 'decomposition', 'is', 'a', 'powerful', 'computational', 'tool', 'for', 'multi', '##way', 'data', 'analysis', '.', 'many', 'popular', 'tensor', 'decomposition', 'approaches', '-', '-', '-', 'such', 'as', 'the', 'tu', '##ck', '##er', 'decomposition', 'and']

### 4.7. Tokenization + Label Alignment

In [ ]:
def tokenize_and_align_labels(examples):

    tokenized_inputs = tokenizer(
        examples["tokens"],
        truncation=True,
        max_length=512,
        is_split_into_words=True
    )

    labels = []

    for i, label in enumerate(examples["labels"]):

        word_ids = tokenized_inputs.word_ids(
            batch_index=i
        )

        previous_word_idx = None

        label_ids = []

        for word_idx in word_ids:

            if word_idx is None:

                label_ids.append(-100)

            elif word_idx != previous_word_idx:

                label_ids.append(
                    label[word_idx]
                )

            else:

                label_ids.append(-100)

            previous_word_idx = word_idx

        labels.append(label_ids)

    tokenized_inputs["labels"] = labels

    return tokenized_inputs

In [ ]:
tokenized_train_ds = train_ds.map(
    tokenize_and_align_labels,
    batched=True
)

tokenized_val_ds = val_ds.map(
    tokenize_and_align_labels,
    batched=True
)

tokenized_test_ds = test_ds.map(
    tokenize_and_align_labels,
    batched=True
)

Map:   0%|          | 0/2740 [00:00<?, ? examples/s]

Map:   0%|          | 0/343 [00:00<?, ? examples/s]

Map:   0%|          | 0/343 [00:00<?, ? examples/s]

#### verify

In [ ]:
print(tokenized_train_ds)

print(tokenized_val_ds)

print(tokenized_test_ds)

Dataset({
    features: ['id', 'tokens', 'ner_tags', 'labels', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 2740
})
Dataset({
    features: ['id', 'tokens', 'ner_tags', 'labels', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 343
})
Dataset({
    features: ['id', 'tokens', 'ner_tags', 'labels', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 343
})

In [ ]:
sample = tokenized_train_ds[0]

print(sample.keys())

dict_keys(['id', 'tokens', 'ner_tags', 'labels', 'input_ids', 'token_type_ids', 'attention_mask'])

In [ ]:
sample = tokenized_train_ds[0]

tokens = tokenizer.convert_ids_to_tokens(
    sample["input_ids"]
)

for t, l in zip(tokens[:100], sample["labels"][:100]):
    print(t, l)

[CLS] -100
tensor 8
decomposition 8
is 8
a 8
powerful 8
computational 8
tool 8
for 8
multi 8
##way -100
data 8
analysis 8
. 8
many 8
popular 8
tensor 8
decomposition 8
approaches 8
- 8
- 8
- 8
such 8
as 8
the 8
tu 0
##ck -100
##er -100
decomposition 4
and 8
cand 0
##ecom -100
##p -100
/ 4
para 4
##fac -100
( 8
cp 8
) 8
- 8
- 8
- 8
amount 8
to 8
multi 8
- 8
linear 8
factorization 8
. 8
they 8
are 8
insufficient 8
to 8
model 8
( 8
i 8
) 8
complex 8
interactions 8
between 8
data 8
entities 8
, 8
( 8
ii 8
) 8
various 8
data 8
types 8
( 8
e 8
. 8
g 8
. 8
missing 8
data 8
and 8
binary 8
data 8
) 8
, 8
and 8
( 8
iii 8
) 8
noisy 8
observations 8
and 8
outliers 8
. 8
to 8
address 8
these 8
issues 8
, 8
we 8
propose 8
tensor 0
- 4
vari 4

#### Check Sequence Lengths

In [ ]:
lengths = [
    len(x)
    for x in tokenized_train_ds["input_ids"]
]

print("Max Length :", max(lengths))
print("Min Length :", min(lengths))
print("Average Length :", sum(lengths)/len(lengths))

Max Length : 512
Min Length : 30
Average Length : 214.00620437956204

#### Count Truncated Samples

In [ ]:
count = sum(
    1
    for x in tokenized_train_ds["input_ids"]
    if len(x) >= 512
)

print("Sequences reaching 512:", count)
print("Percentage:", round(100 * count / len(tokenized_train_ds), 2), "%")

Sequences reaching 512: 1
Percentage: 0.04 %

#### Verify Label IDs

In [ ]:
valid_ids = set(label2id.values())

invalid = 0

for sample in tokenized_train_ds:

    for lbl in sample["labels"]:

        if lbl == -100:
            continue

        if lbl not in valid_ids:
            invalid += 1

print("Invalid Labels:", invalid)

Invalid Labels: 0

#### Count Labels After Tokenization

In [ ]:
from collections import Counter

counter = Counter()

for sample in tokenized_train_ds:

    for lbl in sample["labels"]:

        if lbl != -100:
            counter[lbl] += 1

for k, v in sorted(counter.items()):
    print(id2label[k], v)

B-ALGORITHM 12887
B-DATASET 1942
B-METRIC 1324
B-TASK 3567
I-ALGORITHM 12279
I-DATASET 1179
I-METRIC 743
I-TASK 5445
O 541531

In [ ]:
print("Train:", len(tokenized_train_ds))
print("Val:", len(tokenized_val_ds))
print("Test:", len(tokenized_test_ds))

print("Labels:", len(label2id))

Train: 2740
Val: 343
Test: 343
Labels: 9

#### Save Tokenized Datasets

In [ ]:
tokenized_train_ds.save_to_disk(
    f"tokenized_train_{NUM_PAPERS}"
)

tokenized_val_ds.save_to_disk(
    f"tokenized_val_{NUM_PAPERS}"
)

tokenized_test_ds.save_to_disk(
    f"tokenized_test_{NUM_PAPERS}"
)

Saving the dataset (0/1 shards):   0%|          | 0/2740 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/343 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/343 [00:00<?, ? examples/s]

## 🌟 STEP 5 - Fine-tuning SciBERT

### → Change values here

In [ ]:
# ==========================
# CONFIGURATION
# ==========================

MODEL_NAME = "allenai/scibert_scivocab_uncased"

label_map_json = f"label_mapping_{NUM_PAPERS}.json"

MODEL_DIR = f"scibert_ner_model_trained_on_{NUM_PAPERS}"
MODEL_ZIP = f"scibert_ner_model_trained_on_{NUM_PAPERS}.zip"

### 5.1. Install Libraries

In [ ]:
!pip install transformers datasets seqeval accelerate -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for seqeval (setup.py) ... done

In [ ]:
import json
import numpy as np

from datasets import load_from_disk

from transformers import (
    AutoModelForTokenClassification,
    AutoTokenizer,
    DataCollatorForTokenClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback
)

from seqeval.metrics import (
    precision_score,
    recall_score,
    f1_score,
    accuracy_score
)

### 5.2. Load Tokenized Datasets + Label Mapping + SciBERT Tokenizer + SciBERT Model + Data Collator

In [ ]:
tokenized_train_ds = load_from_disk(
    f"tokenized_train_{NUM_PAPERS}"
)

tokenized_val_ds = load_from_disk(
    f"tokenized_val_{NUM_PAPERS}"
)

tokenized_test_ds = load_from_disk(
    f"tokenized_test_{NUM_PAPERS}"
)

print(tokenized_train_ds)
print(tokenized_val_ds)
print(tokenized_test_ds)

Dataset({
    features: ['id', 'tokens', 'ner_tags', 'labels', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 2740
})
Dataset({
    features: ['id', 'tokens', 'ner_tags', 'labels', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 343
})
Dataset({
    features: ['id', 'tokens', 'ner_tags', 'labels', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 343
})

In [ ]:
with open(label_map_json, "r") as f:
    mappings = json.load(f)

label2id = mappings["label2id"]

id2label = {
    int(k): v
    for k, v in mappings["id2label"].items()
}

print(label2id)

{'B-ALGORITHM': 0, 'B-DATASET': 1, 'B-METRIC': 2, 'B-TASK': 3, 'I-ALGORITHM': 4, 'I-DATASET': 5, 'I-METRIC': 6, 'I-TASK': 7, 'O': 8}

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

In [ ]:
model = AutoModelForTokenClassification.from_pretrained(
    MODEL_NAME,
    num_labels=len(label2id),
    id2label=id2label,
    label2id=label2id
)

print("SciBERT Loaded")

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  442MB

pytorch_model.bin: downloading bytes:           |  0.00B

model.safetensors: reconstructing file:   0%|          |  0.00B /  442MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: allenai/scibert_scivocab_uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

SciBERT Loaded

In [ ]:
data_collator = DataCollatorForTokenClassification(
    tokenizer=tokenizer
)

### 5.3. Compute Metrics Function

In [ ]:
def compute_metrics(p):

    predictions, labels = p

    predictions = np.argmax(
        predictions,
        axis=2
    )

    true_predictions = [
        [
            id2label[p]
            for p, l in zip(pred, lab)
            if l != -100
        ]
        for pred, lab in zip(
            predictions,
            labels
        )
    ]

    true_labels = [
        [
            id2label[l]
            for p, l in zip(pred, lab)
            if l != -100
        ]
        for pred, lab in zip(
            predictions,
            labels
        )
    ]

    return {
        "precision":
            precision_score(
                true_labels,
                true_predictions
            ),
        "recall":
            recall_score(
                true_labels,
                true_predictions
            ),
        "f1":
            f1_score(
                true_labels,
                true_predictions
            ),
        "accuracy":
            accuracy_score(
                true_labels,
                true_predictions
            )
    }

### 5.4. Training Arguments

In [ ]:
training_args = TrainingArguments(

    output_dir=MODEL_DIR,

    eval_strategy="epoch",

    save_strategy="epoch",

    learning_rate=2e-5,

    per_device_train_batch_size=8,

    per_device_eval_batch_size=8,

    num_train_epochs=5,

    weight_decay=0.01,

    load_best_model_at_end=True,

    metric_for_best_model="f1",

    greater_is_better=True,

    save_total_limit=2,

    logging_steps=50,

    report_to="none",

    seed=SEED
)

In [ ]:
early_stopping = EarlyStoppingCallback(
    early_stopping_patience=2
)

### 5.5. Create Trainer &  Train Model

In [ ]:
trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=tokenized_train_ds,

    eval_dataset=tokenized_val_ds,

    processing_class=tokenizer,

    data_collator=data_collator,

    compute_metrics=compute_metrics,

    callbacks=[early_stopping]
)

In [ ]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=1715, training_loss=0.05551742831402548, metrics={'train_runtime': 1011.4912, 'train_samples_per_second': 13.544, 'train_steps_per_second': 1.696, 'total_flos': 2199482155847520.0, 'train_loss': 0.05551742831402548, 'epoch': 5.0})

### 5.6. Evaluate on Validation Set + Test Set

In [ ]:
val_results = trainer.evaluate(
    tokenized_val_ds
)

print(val_results)

{'eval_loss': 0.10497236996889114, 'eval_precision': 0.6460950300382304, 'eval_recall': 0.6987595983461311, 'eval_f1': 0.6713961407491486, 'eval_accuracy': 0.9711975517919023}

In [ ]:
test_results = trainer.evaluate(
    tokenized_test_ds
)

print(test_results)

{'eval_loss': 0.08661332726478577, 'eval_precision': 0.6572052401746725, 'eval_recall': 0.7120047309284447, 'eval_f1': 0.683508373545274, 'eval_accuracy': 0.9749666221628839}

### 5.7. Save Final Model

In [ ]:
MODEL_DIR

'scibert_ner_model_trained_on_3426'

In [ ]:
trainer.save_model(MODEL_DIR)

tokenizer.save_pretrained(MODEL_DIR)

print("Model Saved")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model Saved

In [ ]:
import shutil

shutil.make_archive(
    MODEL_DIR,
    "zip",
    MODEL_DIR
)

print("ZIP Created")

ZIP Created

In [ ]:
print(MODEL_DIR)

scibert_ner_model_trained_on_3426

## 🌟 STEP 6 - Load & Evaluate the trained NER model

### → Change values here

In [ ]:
# ==========================
# CONFIGURATION
# ==========================

input_NORMALIZED_GOLD_json = f"normalized_gold_annotations_{NUM_PAPERS}.json"

model_path_check = "/content/drive/MyDrive/Colab Notebooks/CBSOT Internship/Project-2 Files" ##

MODEL_NAME = f"scibert_ner_model_trained_on_{NUM_PAPERS}"

model_path = f"/content/drive/MyDrive/Colab Notebooks/CBSOT Internship/Project-2 Files/{MODEL_NAME}"

OUTPUT_pred_JSON = f"prediction_on_{NUM_PAPERS}.json"

### 6.1. Import Lib & Load "normalized_gold_annotations_x.json" file

In [ ]:
import json
import torch
from tqdm import tqdm
from transformers import AutoTokenizer
from transformers import AutoModelForTokenClassification

In [ ]:
input_NORMALIZED_GOLD_json = f"normalized_gold_annotations_{NUM_PAPERS}.json"

with open(input_NORMALIZED_GOLD_json, "r", encoding="utf-8") as f:
    data = json.load(f)

print("Total papers:", len(data))

Total papers: 3426

#### 6.1.1. Mount the Drive and Load Trained SciBERT NER Model

In [ ]:
import os
from google.colab import drive

if os.path.exists("/content/drive/MyDrive"):
    print("Google Drive is already mounted.")
else:
    drive.mount("/content/drive")
    print("Google Drive mounted successfully.")

Google Drive is already mounted.

In [ ]:
import os
model_path_check = "/content/drive/MyDrive/Colab Notebooks/CBSOT Internship/Project-2 Files" ##
print("Files/Folders in 'Project-2 Files':")
print(os.listdir(model_path_check))
print()
print(f"Files inside '{MODEL_NAME}':")
print(os.listdir(model_path))

Files/Folders in 'Project-2 Files':
['paper_embeddings.npy', 'paper_faiss.index', 'processed_df.pkl', 'saved_scibert_ner', 'scibert_ner_model_trained_on_3426']

Files inside 'scibert_ner_model_trained_on_3426':
['model.safetensors', 'training_args.bin', 'config.json', 'tokenizer_config.json', 'tokenizer.json']

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForTokenClassification.from_pretrained(model_path)
model.eval()

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForTokenClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(31090, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=9, bias=True)
)

### 6.2. Define the "extract_entities()" function

In [ ]:
def extract_entities(text):

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=512
    )

    with torch.no_grad():
        outputs = model(**inputs)

    predictions = torch.argmax(
        outputs.logits,
        dim=2
    )

    tokens = tokenizer.convert_ids_to_tokens(
        inputs["input_ids"][0]
    )

    labels = [
        model.config.id2label[p.item()]
        for p in predictions[0]
    ]

    results = []

    current_tokens = []
    current_label = None

    # Convert BIO labels to entities
    for token, label in zip(tokens, labels):

        if token in ["[CLS]", "[SEP]", "[PAD]"]:
            continue

        if label.startswith("B-"):

            if current_tokens:
                results.append({
                    "entity": tokenizer.convert_tokens_to_string(
                        current_tokens
                    ).lower().strip(),
                    "label": current_label
                })

            current_tokens = [token]
            current_label = label[2:]

        elif (
            label.startswith("I-")
            and current_label == label[2:]
        ):

            current_tokens.append(token)

        else:

            if current_tokens:
                results.append({
                    "entity": tokenizer.convert_tokens_to_string(
                        current_tokens
                    ).lower().strip(),
                    "label": current_label
                })

            current_tokens = []
            current_label = None

    # Save last entity
    if current_tokens:
        results.append({
            "entity": tokenizer.convert_tokens_to_string(
                current_tokens
            ).lower().strip(),
            "label": current_label
        })

    return results

#### 6.2.1. Check

In [ ]:
paper = data[0]

print("GOLD")
print(paper["entities"])

print("\nPRED")
print(extract_entities(paper["abstract"]))

GOLD
[{'entity': 'epsilon-Consistent Mixup', 'label': 'ALGORITHM'}, {'entity': 'Mixup', 'label': 'ALGORITHM'}, {'entity': 'SVHN', 'label': 'DATASET'}, {'entity': 'CIFAR-10', 'label': 'DATASET'}, {'entity': 'semi-supervised classification', 'label': 'TASK'}, {'entity': 'Accuracy', 'label': 'METRIC'}]

PRED
[{'entity': 'epsilon - consistent mixup', 'label': 'ALGORITHM'}, {'entity': 'epsilonmu', 'label': 'ALGORITHM'}, {'entity': 'epsilonmu', 'label': 'ALGORITHM'}, {'entity': 'mixup', 'label': 'ALGORITHM'}, {'entity': 'semi - supervised classification', 'label': 'TASK'}, {'entity': 'accuracy', 'label': 'METRIC'}, {'entity': 'svhn', 'label': 'DATASET'}, {'entity': 'cifar10', 'label': 'DATASET'}, {'entity': 'epsilonmu', 'label': 'ALGORITHM'}, {'entity': 'mixup', 'label': 'ALGORITHM'}, {'entity': 'epsilonmu', 'label': 'ALGORITHM'}, {'entity': 'epsilonmu', 'label': 'ALGORITHM'}, {'entity': 'mixup', 'label': 'ALGORITHM'}]

In [ ]:
inputs = tokenizer(
    paper["abstract"],
    return_tensors="pt",
    truncation=True,
    max_length=512
)

with torch.no_grad():
    outputs = model(**inputs)

predictions = torch.argmax(outputs.logits, dim=2)

tokens = tokenizer.convert_ids_to_tokens(
    inputs["input_ids"][0]
)

labels = [
    model.config.id2label[p.item()]
    for p in predictions[0]
]

for token, label in zip(tokens, labels):

    if token in ["[CLS]", "[SEP]", "[PAD]"]:
        continue

    if "eps" in token or "##il" in token or "##on" in token:
        print(token, " ---> ", label)

eps  --->  B-ALGORITHM
##il  --->  I-ALGORITHM
##on  --->  I-ALGORITHM
eps  --->  B-ALGORITHM
##il  --->  I-ALGORITHM
##on  --->  I-ALGORITHM
eps  --->  B-ALGORITHM
##il  --->  I-ALGORITHM
##on  --->  I-ALGORITHM
eps  --->  B-ALGORITHM
##il  --->  I-ALGORITHM
##on  --->  I-ALGORITHM
eps  --->  B-ALGORITHM
##il  --->  I-ALGORITHM
##on  --->  I-ALGORITHM
eps  --->  B-ALGORITHM
##il  --->  I-ALGORITHM
##on  --->  I-ALGORITHM

#### 6.2.2. Normalize

In [ ]:
import re

def normalize_entity(text):

    text = text.lower().strip()

    # remove spaces
    text = re.sub(r"\s+", "", text)

    # remove hyphens
    text = text.replace("-", "")

    return text

#### 6.2.3. Predict the entities for first 10 papers

In [ ]:
correct = 0
gold_total = 0
pred_total = 0

sample_data = data[:10]

for i, paper in enumerate(sample_data):

    gold = {
        (
            normalize_entity(e["entity"]),
            e["label"]
        )
        for e in paper["entities"]
    }

    preds = extract_entities(paper["abstract"])

    pred = {
        (
            normalize_entity(e["entity"]),
            e["label"]
        )
        for e in preds
    }

    # Evaluation
    correct += len(gold & pred)
    gold_total += len(gold)
    pred_total += len(pred)

    # Per-paper analysis
    print("\n" + "=" * 100)
    print(f"PAPER #{i+1}")

    print("\nMATCHES")
    print(gold & pred)

    print("\nMISSED (Gold but not Pred)")
    print(gold - pred)

    print("\nEXTRA (Pred but not Gold)")
    print(pred - gold)


# ==========================
# OVERALL METRICS
# ==========================

precision = correct / pred_total if pred_total else 0
recall = correct / gold_total if gold_total else 0

f1 = (
    2 * precision * recall / (precision + recall)
    if precision + recall > 0
    else 0
)

print("\n" + "=" * 100)
print("FINAL RESULTS")
print("=" * 100)

print("Gold      :", gold_total)
print("Predicted :", pred_total)
print("Correct   :", correct)

print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1        : {f1:.4f}")

====================================================================================================
PAPER #1

MATCHES
{('accuracy', 'METRIC'), ('epsilonconsistentmixup', 'ALGORITHM'), ('cifar10', 'DATASET'), ('semisupervisedclassification', 'TASK'), ('svhn', 'DATASET'), ('mixup', 'ALGORITHM')}

MISSED (Gold but not Pred)
set()

EXTRA (Pred but not Gold)
{('epsilonmu', 'ALGORITHM')}

====================================================================================================
PAPER #2

MATCHES
{('anomalydetection', 'TASK'), ('graphneuralnetwork', 'ALGORITHM'), ('graphbasedautoencoders', 'ALGORITHM')}

MISSED (Gold but not Pred)
{('autoencoder', 'ALGORITHM')}

EXTRA (Pred but not Gold)
set()

====================================================================================================
PAPER #3

MATCHES
{('gaussianmodels', 'ALGORITHM'), ('featureselection', 'TASK')}

MISSED (Gold but not Pred)
set()

EXTRA (Pred but not Gold)
{('jointly', 'ALGORITHM')}

====================================================================================================
PAPER #4

MATCHES
{('convolutionalneuralnetwork', 'ALGORITHM'), ('accuracy', 'METRIC'), ('skinlesiondetection', 'TASK')}

MISSED (Gold but not Pred)
{('resnet50', 'ALGORITHM'), ('vgg19', 'ALGORITHM'), ('densenet121', 'ALGORITHM'), ('resnet34', 'ALGORITHM')}

EXTRA (Pred but not Gold)
{('resnet', 'ALGORITHM'), ('vgg', 'ALGORITHM'), ('densenet', 'ALGORITHM')}

====================================================================================================
PAPER #5

MATCHES
set()

MISSED (Gold but not Pred)
set()

EXTRA (Pred but not Gold)
set()

====================================================================================================
PAPER #6

MATCHES
{('featureextraction', 'TASK'), ('deepsamplelearningalgorithm', 'ALGORITHM'), ('deepsampleslearningalgorithm', 'ALGORITHM'), ('iterativemeanclustering', 'ALGORITHM'), ('deepfeaturelearningalgorithm', 'ALGORITHM'), ('fewshotlearning', 'TASK'), ('deepstackedgroupsparseautoencoder', 'ALGORITHM'), ('deepdoublesidelearningensemblemodel', 'ALGORITHM'), ('featurereduction', 'TASK'), ('baggingensemblelearning', 'ALGORITHM')}

MISSED (Gold but not Pred)
{('l1regularizationfeatureselectionmethod', 'ALGORITHM'), ('featureselection', 'TASK')}

EXTRA (Pred but not Gold)
{('feature', 'TASK'), ('l1regularizationfeatureselection', 'ALGORITHM')}

====================================================================================================
PAPER #7

MATCHES
{('closenesstesting', 'TASK')}

MISSED (Gold but not Pred)
{('typeierror', 'METRIC'), ('identitytesting', 'TASK'), ('typeiierror', 'METRIC')}

EXTRA (Pred but not Gold)
{('identity', 'TASK')}

====================================================================================================
PAPER #8

MATCHES
set()

MISSED (Gold but not Pred)
set()

EXTRA (Pred but not Gold)
set()

====================================================================================================
PAPER #9

MATCHES
{('knnclassification', 'TASK'), ("wordmover'sdistance", 'ALGORITHM')}

MISSED (Gold but not Pred)
set()

EXTRA (Pred but not Gold)
set()

====================================================================================================
PAPER #10

MATCHES
{('speakerdiarization', 'TASK'), ('multinomialloss', 'ALGORITHM'), ('f1', 'METRIC'), ('diarizationerrorrate', 'METRIC'), ('dynamictripletloss', 'ALGORITHM')}

MISSED (Gold but not Pred)
set()

EXTRA (Pred but not Gold)
set()

====================================================================================================
FINAL RESULTS
====================================================================================================
Gold      : 42
Predicted : 40
Correct   : 32
Precision : 0.8000
Recall    : 0.7619
F1        : 0.7805

### 6.3. Predict & Save "prediction_on_x(i.e no. of rows).json"

In [ ]:
import json

correct = 0
gold_total = 0
pred_total = 0

all_predictions = []

SAVE_EVERY = 20

for idx, paper in enumerate(data, start=1):

    abstract = paper["abstract"]

    gold = {
        (normalize_entity(e["entity"]), e["label"])
        for e in paper["entities"]
    }

    preds = extract_entities(abstract)

    # Save predictions
    all_predictions.append({
            "id": paper["id"],
            "abstract": abstract,
            "predicted_entities": preds
    })

    pred = {
        (normalize_entity(e["entity"]), e["label"])
        for e in preds
    }

    correct += len(gold & pred)
    gold_total += len(gold)
    pred_total += len(pred)

    # Save every 20 papers
    if idx % SAVE_EVERY == 0:
        with open(OUTPUT_pred_JSON, "w", encoding="utf-8") as f:
            json.dump(all_predictions, f, indent=2, ensure_ascii=False)

        print(f"Saved progress: {idx} papers")

# Final save
with open(OUTPUT_pred_JSON, "w", encoding="utf-8") as f:
    json.dump(all_predictions, f, indent=2, ensure_ascii=False)

print("\nFinal save completed.")

Saved progress: 20 papers
Saved progress: 40 papers
Saved progress: 60 papers
Saved progress: 80 papers
Saved progress: 100 papers
Saved progress: 120 papers
Saved progress: 140 papers
Saved progress: 160 papers
Saved progress: 180 papers
Saved progress: 200 papers
Saved progress: 220 papers
Saved progress: 240 papers
Saved progress: 260 papers
Saved progress: 280 papers
Saved progress: 300 papers
Saved progress: 320 papers
Saved progress: 340 papers
Saved progress: 360 papers
Saved progress: 380 papers
Saved progress: 400 papers
Saved progress: 420 papers
Saved progress: 440 papers
Saved progress: 460 papers
Saved progress: 480 papers
Saved progress: 500 papers
Saved progress: 520 papers
Saved progress: 540 papers
Saved progress: 560 papers
Saved progress: 580 papers
Saved progress: 600 papers
Saved progress: 620 papers
Saved progress: 640 papers
Saved progress: 660 papers
Saved progress: 680 papers
Saved progress: 700 papers
Saved progress: 720 papers
Saved progress: 740 papers
Saved progress: 760 papers
Saved progress: 780 papers
Saved progress: 800 papers
Saved progress: 820 papers
Saved progress: 840 papers
Saved progress: 860 papers
Saved progress: 880 papers
Saved progress: 900 papers
Saved progress: 920 papers
Saved progress: 940 papers
Saved progress: 960 papers
Saved progress: 980 papers
Saved progress: 1000 papers
Saved progress: 1020 papers
Saved progress: 1040 papers
Saved progress: 1060 papers
Saved progress: 1080 papers
Saved progress: 1100 papers
Saved progress: 1120 papers
Saved progress: 1140 papers
Saved progress: 1160 papers
Saved progress: 1180 papers
Saved progress: 1200 papers
Saved progress: 1220 papers
Saved progress: 1240 papers
Saved progress: 1260 papers
Saved progress: 1280 papers
Saved progress: 1300 papers
Saved progress: 1320 papers
Saved progress: 1340 papers
Saved progress: 1360 papers
Saved progress: 1380 papers
Saved progress: 1400 papers
Saved progress: 1420 papers
Saved progress: 1440 papers
Saved progress: 1460 papers
Saved progress: 1480 papers
Saved progress: 1500 papers
Saved progress: 1520 papers
Saved progress: 1540 papers
Saved progress: 1560 papers
Saved progress: 1580 papers
Saved progress: 1600 papers
Saved progress: 1620 papers
Saved progress: 1640 papers
Saved progress: 1660 papers
Saved progress: 1680 papers
Saved progress: 1700 papers
Saved progress: 1720 papers
Saved progress: 1740 papers
Saved progress: 1760 papers
Saved progress: 1780 papers
Saved progress: 1800 papers
Saved progress: 1820 papers
Saved progress: 1840 papers
Saved progress: 1860 papers
Saved progress: 1880 papers
Saved progress: 1900 papers
Saved progress: 1920 papers
Saved progress: 1940 papers
Saved progress: 1960 papers
Saved progress: 1980 papers
Saved progress: 2000 papers
Saved progress: 2020 papers
Saved progress: 2040 papers
Saved progress: 2060 papers
Saved progress: 2080 papers
Saved progress: 2100 papers
Saved progress: 2120 papers
Saved progress: 2140 papers
Saved progress: 2160 papers
Saved progress: 2180 papers
Saved progress: 2200 papers
Saved progress: 2220 papers
Saved progress: 2240 papers
Saved progress: 2260 papers
Saved progress: 2280 papers
Saved progress: 2300 papers
Saved progress: 2320 papers
Saved progress: 2340 papers
Saved progress: 2360 papers
Saved progress: 2380 papers
Saved progress: 2400 papers
Saved progress: 2420 papers
Saved progress: 2440 papers
Saved progress: 2460 papers
Saved progress: 2480 papers
Saved progress: 2500 papers
Saved progress: 2520 papers
Saved progress: 2540 papers
Saved progress: 2560 papers
Saved progress: 2580 papers
Saved progress: 2600 papers
Saved progress: 2620 papers
Saved progress: 2640 papers
Saved progress: 2660 papers
Saved progress: 2680 papers
Saved progress: 2700 papers
Saved progress: 2720 papers
Saved progress: 2740 papers
Saved progress: 2760 papers
Saved progress: 2780 papers
Saved progress: 2800 papers
Saved progress: 2820 papers
Saved progress: 2840 papers
Saved progress: 2860 papers
Saved progress: 2880 papers
Saved progress: 2900 papers
Saved progress: 2920 papers
Saved progress: 2940 papers
Saved progress: 2960 papers
Saved progress: 2980 papers
Saved progress: 3000 papers
Saved progress: 3020 papers
Saved progress: 3040 papers
Saved progress: 3060 papers
Saved progress: 3080 papers
Saved progress: 3100 papers
Saved progress: 3120 papers
Saved progress: 3140 papers
Saved progress: 3160 papers
Saved progress: 3180 papers
Saved progress: 3200 papers
Saved progress: 3220 papers
Saved progress: 3240 papers
Saved progress: 3260 papers
Saved progress: 3280 papers
Saved progress: 3300 papers
Saved progress: 3320 papers
Saved progress: 3340 papers
Saved progress: 3360 papers
Saved progress: 3380 papers
Saved progress: 3400 papers
Saved progress: 3420 papers

Final save completed.

### 6.4. Compute Precision, Recall, F1 & Display Results

In [ ]:
precision = (
    correct / pred_total
    if pred_total > 0
    else 0
)

recall = (
    correct / gold_total
    if gold_total > 0
    else 0
)

f1 = (
    2 * precision * recall /
    (precision + recall)
    if precision + recall > 0
    else 0
)

In [ ]:
print("FINAL RESULTS")

print("Gold Entities      :", gold_total)
print("Predicted Entities :", pred_total)
print("Correct Matches    :", correct)

print(f"\nPrecision = {precision:.4f}")
print(f"Recall    = {recall:.4f}")
print(f"F1        = {f1:.4f}")

FINAL RESULTS
Gold Entities      : 13022
Predicted Entities : 13008
Correct Matches    : 10797

Precision = 0.8300
Recall    = 0.8291
F1        = 0.8296

In [ ]:
print(all_predictions[0])

{'id': 0, 'abstract': "In this paper we propose epsilon-Consistent Mixup (epsilonmu). epsilonmu is a data-based structural regularization technique that combines Mixup's linear interpolation with consistency regularization in the Mixup direction, by compelling a simple adaptive tradeoff between the two. This learnable combination of consistency and interpolation induces a more flexible structure on the evolution of the response across the feature space and is shown to improve semi-supervised classification accuracy on the SVHN and CIFAR10 benchmark datasets, yielding the largest gains in the most challenging low label-availability scenarios. Empirical studies comparing epsilonmu and Mixup are presented and provide insight into the mechanisms behind epsilonmu's effectiveness. In particular, epsilonmu is found to produce more accurate synthetic labels and more confident predictions than Mixup.", 'predicted_entities': [{'entity': 'epsilon - consistent mixup', 'label': 'ALGORITHM'}, {'entity': 'epsilonmu', 'label': 'ALGORITHM'}, {'entity': 'epsilonmu', 'label': 'ALGORITHM'}, {'entity': 'mixup', 'label': 'ALGORITHM'}, {'entity': 'semi - supervised classification', 'label': 'TASK'}, {'entity': 'accuracy', 'label': 'METRIC'}, {'entity': 'svhn', 'label': 'DATASET'}, {'entity': 'cifar10', 'label': 'DATASET'}, {'entity': 'epsilonmu', 'label': 'ALGORITHM'}, {'entity': 'mixup', 'label': 'ALGORITHM'}, {'entity': 'epsilonmu', 'label': 'ALGORITHM'}, {'entity': 'epsilonmu', 'label': 'ALGORITHM'}, {'entity': 'mixup', 'label': 'ALGORITHM'}]}

### 6.5. Save only the unique entities in "prediction_unique_entities_on_x(i.e no. of rows).json"

In [ ]:
OUTPUT_unique_pred_JSON = f"predicted_unique_entities_on_{NUM_PAPERS}.json"

In [ ]:
unique_predictions = []

for paper in all_predictions:

    seen = set()
    unique_entities = []

    for ent in paper["predicted_entities"]:

        key = (
            ent["entity"].lower().strip(),
            ent["label"]
        )

        if key not in seen:

            seen.add(key)

            unique_entities.append({
                "entity": ent["entity"],
                "label": ent["label"]
            })

    unique_predictions.append({
        "id": paper["id"],
        "abstract": paper["abstract"],
        "predicted_entities": unique_entities
    })

In [ ]:
with open(
    OUTPUT_unique_pred_JSON,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        unique_predictions,
        f,
        indent=2,
        ensure_ascii=False
    )

print("Saved:", OUTPUT_unique_pred_JSON)

Saved: predicted_entities_unique_3426.json